const districtData = [
    { dis: "Bagherhat", cp: "34.0", count: 1 },
    { dis: "Bagherhat", cp: "40.0", count: 4 },
    { dis: "Bagherhat", cp: "60.0", count: 3 },
    { dis: "Bagherhat", cp: "7.0", count: 6 },

    { dis: "Bandarban", cp: "0.0", count: 8 },
    { dis: "Bandarban", cp: "12.0", count: 2 },
    { dis: "Bandarban", cp: "35.0", count: 1 },

    { dis: "Barishal", cp: "10.0", count: 1 },
    { dis: "Barishal", cp: "12.0", count: 3 },
    { dis: "Barishal", cp: "2.0", count: 1 },
    { dis: "Barishal", cp: "22.0", count: 2 },
    { dis: "Barishal", cp: "3.0", count: 1 },
    { dis: "Barishal", cp: "46.0", count: 2 },

    { dis: "Bogura", cp: "1.0", count: 6 },
    { dis: "Bogura", cp: "24.0", count: 2 },

    { dis: "Chadpur", cp: "0.0", count: 1 },
    { dis: "Chadpur", cp: "1.0", count: 4 },
    { dis: "Chadpur", cp: "2.0", count: 3 },
    { dis: "Chadpur", cp: "217.0", count: 1 },
    { dis: "Chadpur", cp: "43.0", count: 1 },
    { dis: "Chadpur", cp: "60.0", count: 1 },

    { dis: "Chattogram", cp: "0.0", count: 4 },
    { dis: "Chattogram", cp: "1.0", count: 3 },
    { dis: "Chattogram", cp: "12.0", count: 4 },
    { dis: "Chattogram", cp: "3.0", count: 3 },
    { dis: "Chattogram", cp: "36.0", count: 1 },
    { dis: "Chittagong", cp: "0.0", count: 5 },
    { dis: "Chittagong", cp: "1.0", count: 2 },
    { dis: "Chittagong", cp: "3.0", count: 5 },

    { dis: "Cumilla", cp: "0.0", count: 1 },
    { dis: "Cumilla", cp: "183.0", count: 1 },
    { dis: "Cumilla", cp: "2.0", count: 2 },
    { dis: "Cumilla", cp: "217.0", count: 2 },
    { dis: "Cumilla", cp: "60.0", count: 1 },
    { dis: "Cumilla", cp: "7.0", count: 6 },

    { dis: "Dhaka", cp: "0.0", count: 4 },
    { dis: "Dhaka", cp: "2.0", count: 7 },
    { dis: "Dhaka", cp: "27.0", count: 4 },

    { dis: "Dinajpur", cp: "1.0", count: 13 },
    { dis: "Dinajpur", cp: "13.0", count: 1 },
    { dis: "Dinajpur", cp: "14.0", count: 1 },
    { dis: "Dinajpur", cp: "2.0", count: 3 },

    { dis: "Faridpur", cp: "0.0", count: 1 },
    { dis: "Faridpur", cp: "10.0", count: 2 },
    { dis: "Faridpur", cp: "12.0", count: 2 },
    { dis: "Faridpur", cp: "2.0", count: 1 },
    { dis: "Faridpur", cp: "217.0", count: 2 },
    { dis: "Faridpur", cp: "24.0", count: 4 },
    { dis: "Faridpur", cp: "27.0", count: 5 },
    { dis: "Faridpur", cp: "58.0", count: 2 },
    { dis: "Faridpur", cp: "7.0", count: 2 },
    { dis: "Faridpur", cp: "9.0", count: 3 },

    { dis: "Feni", cp: "1.0", count: 3 },
    { dis: "Feni", cp: "10.0", count: 1 },
    { dis: "Feni", cp: "12.0", count: 2 },

    { dis: "Gaibandha", cp: "1.0", count: 1 },
    { dis: "Gaibandha", cp: "13.0", count: 1 },
    { dis: "Gaibandha", cp: "2.0", count: 3 },
    { dis: "Gaibandha", cp: "24.0", count: 1 },
    { dis: "Gaibandha", cp: "35.0", count: 2 },
    { dis: "Gaibandha", cp: "4.0", count: 4 },
    { dis: "Gaibandha", cp: "9.0", count: 1 },

    { dis: "Habigonj", cp: "2.0", count: 16 },
    { dis: "Habigonj", cp: "35.0", count: 1 },

    { dis: "Joypurhat", cp: "1.0", count: 4 },
    { dis: "Joypurhat", cp: "11.0", count: 1 },
    { dis: "Joypurhat", cp: "122.0", count: 1 },
    { dis: "Joypurhat", cp: "32.0", count: 1 },
    { dis: "Joypurhat", cp: "6.0", count: 7 },
    { dis: "Joypurhat", cp: "7.0", count: 1 },

    { dis: "Khagrachari", cp: "0.0", count: 6 },
    { dis: "Khagrachari", cp: "1.0", count: 2 },
    { dis: "Khagrachari", cp: "3.0", count: 2 },
    { dis: "Khagrachori", cp: "0.0", count: 10 },
    { dis: "Khagrachori", cp: "1.0", count: 3 },

    { dis: "Khulna", cp: "104.0", count: 1 },
    { dis: "Khulna", cp: "153.0", count: 9 },
    { dis: "Khulna", cp: "172.0", count: 3 },
    { dis: "Khulna", cp: "60.0", count: 2 },

    { dis: "Kishoregonj", cp: "1.0", count: 7 },
    { dis: "Kishoregonj", cp: "2.0", count: 13 },
    { dis: "Kishoregonj", cp: "24.0", count: 1 },
    { dis: "Kishoregonj", cp: "9.0", count: 6 },

    { dis: "Kurigram", cp: "1.0", count: 15 },
    { dis: "Kurigram", cp: "10.0", count: 2 },
    { dis: "Kurigram", cp: "2.0", count: 8 },
    { dis: "Kurigram", cp: "35.0", count: 1 },

    { dis: "Kushtia", cp: "0.0", count: 5 },
    { dis: "Kushtia", cp: "14.0", count: 2 },
    { dis: "Kushtia", cp: "2.0", count: 2 },
    { dis: "Kushtia", cp: "28.0", count: 2 },
    { dis: "Kushtia", cp: "5.0", count: 4 },
    { dis: "Kushtia", cp: "7.0", count: 3 },
    { dis: "Kushtia", cp: "9.0", count: 7 },

    { dis: "Lalmonirhat", cp: "1.0", count: 4 },
    { dis: "Lalmonirhat", cp: "10.0", count: 3 },
    { dis: "Lalmonirhat", cp: "2.0", count: 1 },
    { dis: "Lalmonirhat", cp: "250.0", count: 1 },
    { dis: "Lalmonirhat", cp: "64.0", count: 2 },
    { dis: "Lalmonirhat", cp: "9.0", count: 3 },

    { dis: "Manikgonj", cp: "0.0", count: 3 },
    { dis: "Manikgonj", cp: "10.0", count: 1 },
    { dis: "Manikgonj", cp: "16.0", count: 2 },
    { dis: "Manikgonj", cp: "2.0", count: 17 },
    { dis: "Manikgonj", cp: "217.0", count: 2 },
    { dis: "Manikgonj", cp: "27.0", count: 3 },
    { dis: "Manikgonj", cp: "33.0", count: 3 },
    { dis: "Manikgonj", cp: "40.0", count: 1 },
    { dis: "Manikgonj", cp: "9.0", count: 3 },

    { dis: "Munishigonj", cp: "0.0", count: 15 },
    { dis: "Munishigonj", cp: "2.0", count: 4 },
    { dis: "Munishigonj", cp: "40.0", count: 4 },
    { dis: "Munishigonj", cp: "67.0", count: 4 },
    { dis: "Mymenshingh", cp: "0.0", count: 3 },
    { dis: "Mymenshingh", cp: "1.0", count: 17 },
    { dis: "Mymenshingh", cp: "2.0", count: 9 },

    { dis: "Narail", cp: "1.0", count: 1 },
    { dis: "Narail", cp: "2.0", count: 2 },
    { dis: "Narail", cp: "24.0", count: 1 },
    { dis: "Narail", cp: "5.0", count: 3 },
    { dis: "Narail", cp: "7.0", count: 1 },
    { dis: "Narail", cp: "9.0", count: 1 },

    { dis: "Netrokona", cp: "0.0", count: 1 },
    { dis: "Netrokona", cp: "1.0", count: 9 },
    { dis: "Netrokona", cp: "2.0", count: 16 },
    { dis: "Netrokona", cp: "3.0", count: 1 },

    { dis: "Noakhali", cp: "1.0", count: 2 },
    { dis: "Noakhali", cp: "2.0", count: 8 },

    { dis: "Pabna", cp: "0.0", count: 6 },
    { dis: "Pabna", cp: "1.0", count: 2 },
    { dis: "Pabna", cp: "103.0", count: 3 },
    { dis: "Pabna", cp: "11.0", count: 11 },
    { dis: "Pabna", cp: "13.0", count: 1 },
    { dis: "Pabna", cp: "183.0", count: 3 },
    { dis: "Pabna", cp: "2.0", count: 7 },
    { dis: "Pabna", cp: "217.0", count: 9 },
    { dis: "Pabna", cp: "40.0", count: 1 },
    { dis: "Pabna", cp: "58.0", count: 2 },
    { dis: "Pabna", cp: "6.0", count: 4 },
    { dis: "Pabna", cp: "60.0", count: 3 },
    { dis: "Pabna", cp: "7.0", count: 1 },
    { dis: "Pabna", cp: "9.0", count: 1 },
    { dis: "Pabna", cp: "90.0", count: 5 },

    { dis: "Prirozpur", cp: "0.0", count: 1 },
    { dis: "Prirozpur", cp: "12.0", count: 1 },
    { dis: "Prirozpur", cp: "15.0", count: 3 },
    { dis: "Prirozpur", cp: "5.0", count: 1 },

    { dis: "Rajshahi", cp: "0.0", count: 3 },
    { dis: "Rajshahi", cp: "1.0", count: 12 },
    { dis: "Rajshahi", cp: "11.0", count: 11 },
    { dis: "Rajshahi", cp: "13.0", count: 1 },
    { dis: "Rajshahi", cp: "2.0", count: 2 },
    { dis: "Rajshahi", cp: "6.0", count: 14 },

    { dis: "Rangamati", cp: "0.0", count: 1 },

    { dis: "Satkhira", cp: "0.0", count: 2 },
    { dis: "Satkhira", cp: "1.0", count: 5 },
    { dis: "Satkhira", cp: "10.0", count: 4 },
    { dis: "Satkhira", cp: "2.0", count: 1 },
    { dis: "Satkhira", cp: "34.0", count: 6 },
    { dis: "Satkhira", cp: "9.0", count: 3 },

    { dis: "Sherpur", cp: "0.0", count: 6 },
    { dis: "Sherpur", cp: "1.0", count: 20 },
    { dis: "Sherpur", cp: "10.0", count: 4 },
    { dis: "Sherpur", cp: "2.0", count: 5 },
    { dis: "Sherpur", cp: "234.0", count: 2 },
    { dis: "Sherpur", cp: "3.0", count: 2 },
    { dis: "Sherpur", cp: "5.0", count: 7 },

    { dis: "Shirajgonj", cp: "1.0", count: 6 },
    { dis: "Shirajgonj", cp: "2.0", count: 4 },
    { dis: "Shirajgonj", cp: "24.0", count: 3 },
    { dis: "Shirajgonj", cp: "40.0", count: 12 },
    { dis: "Shirajgonj", cp: "7.0", count: 5 },

    { dis: "Shunamgonj", cp: "0.0", count: 3 },
    { dis: "Shunamgonj", cp: "1.0", count: 1 },
    { dis: "Shunamgonj", cp: "12.0", count: 2 },
    { dis: "Shunamgonj", cp: "2.0", count: 9 },

    { dis: "Sirajgang", cp: "1.0", count: 3 },
    { dis: "Sirajgang", cp: "11.0", count: 4 },
    { dis: "Sirajgang", cp: "13.0", count: 2 },
    { dis: "Sirajgang", cp: "2.0", count: 1 },
    { dis: "Sirajgang", cp: "9.0", count: 7 },
    { dis: "Sirajganj", cp: "1.0", count: 2 },
    { dis: "Sirajganj", cp: "11.0", count: 1 },
    { dis: "Sirajganj", cp: "2.0", count: 1 },
    { dis: "Sirajganj", cp: "6.0", count: 8 },

    { dis: "Sylhet", cp: "0.0", count: 4 },
    { dis: "Sylhet", cp: "2.0", count: 9 },
    { dis: "Sylhet", cp: "3.0", count: 6 },

    { dis: "Tangail", cp: "11.0", count: 4 },
    { dis: "Tangail", cp: "17.0", count: 1 },
    { dis: "Tangail", cp: "2.0", count: 6 },
    { dis: "Tangail", cp: "6.0", count: 3 },
];

export default districtData;
