const locationData = [
    {
        Upazila: "Manikgonjsadar",
        Lat: 23.81917,
        Lng: 90.04344,
        Most_Frequent_Cropping_Pattern: "Boro-Fallow-Fallow",
        number_of_unique_cropping_pattern: 8,
        Average_Rainfall_Robi: 72.0,
        Average_Rainfall_Kharif1: 515.0,
        Average_Rainfall_Kharif2: 2030.0,
        Average_Temp_Robi: 21.08,
        Average_Temp_Kharif1: 27.86,
        Average_Temp_Kharif2: 28.48,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Gaibandha-Sadar",
        Lat: 25.32572,
        Lng: 89.57501,
        Most_Frequent_Cropping_Pattern: "Boro-Aus-T.Aman",
        number_of_unique_cropping_pattern: 7,
        Average_Rainfall_Robi: 32.0,
        Average_Rainfall_Kharif1: 411.0,
        Average_Rainfall_Kharif2: 1850.0,
        Average_Temp_Robi: 19.56,
        Average_Temp_Kharif1: 25.89,
        Average_Temp_Kharif2: 28.29,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Bera",
        Lat: 24.08045,
        Lng: 89.62097,
        Most_Frequent_Cropping_Pattern: "Mustard-B.Aus+B.Aman",
        number_of_unique_cropping_pattern: 7,
        Average_Rainfall_Robi: 49.0,
        Average_Rainfall_Kharif1: 290.0,
        Average_Rainfall_Kharif2: 1196.0,
        Average_Temp_Robi: 20.64,
        Average_Temp_Kharif1: 28.4,
        Average_Temp_Kharif2: 28.8,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Sadar",
        Lat: 24.6828,
        Lng: 90.69602,
        Most_Frequent_Cropping_Pattern: "Wheat-Jute-T.Aman",
        number_of_unique_cropping_pattern: 6,
        Average_Rainfall_Robi: 50.1111111111,
        Average_Rainfall_Kharif1: 328.8333333333,
        Average_Rainfall_Kharif2: 1319.1111111111,
        Average_Temp_Robi: 20.1977777778,
        Average_Temp_Kharif1: 27.7883333333,
        Average_Temp_Kharif2: 28.2733333333,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Nalitabari",
        Lat: 25.09778,
        Lng: 90.17867,
        Most_Frequent_Cropping_Pattern: "Boro-Fallow-T.Aman",
        number_of_unique_cropping_pattern: 6,
        Average_Rainfall_Robi: 59.0,
        Average_Rainfall_Kharif1: 465.0,
        Average_Rainfall_Kharif2: 1751.0,
        Average_Temp_Robi: 20.62,
        Average_Temp_Kharif1: 20.03,
        Average_Temp_Kharif2: 34.83,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Narail-Sadar",
        Lat: 23.13467,
        Lng: 89.50075,
        Most_Frequent_Cropping_Pattern: "Fallow-Aus-T.Aman",
        number_of_unique_cropping_pattern: 6,
        Average_Rainfall_Robi: 65.0,
        Average_Rainfall_Kharif1: 273.0,
        Average_Rainfall_Kharif2: 1247.0,
        Average_Temp_Robi: 20.71,
        Average_Temp_Kharif1: 28.4,
        Average_Temp_Kharif2: 28.63,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Kaliganj",
        Lat: 23.97504,
        Lng: 90.54505,
        Most_Frequent_Cropping_Pattern: "Boro-Fallow-T.Aman",
        number_of_unique_cropping_pattern: 6,
        Average_Rainfall_Robi: 33.0,
        Average_Rainfall_Kharif1: 373.0,
        Average_Rainfall_Kharif2: 1717.0,
        Average_Temp_Robi: 19.86,
        Average_Temp_Kharif1: 25.72,
        Average_Temp_Kharif2: 28.25,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Modhukhali",
        Lat: 23.53333,
        Lng: 89.61575,
        Most_Frequent_Cropping_Pattern: "Wheat-Jute-Fallow",
        number_of_unique_cropping_pattern: 6,
        Average_Rainfall_Robi: 74.0,
        Average_Rainfall_Kharif1: 404.0,
        Average_Rainfall_Kharif2: 1412.0,
        Average_Temp_Robi: 21.03,
        Average_Temp_Kharif1: 28.12,
        Average_Temp_Kharif2: 28.73,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Akkelpur",
        Lat: 24.96716,
        Lng: 89.01753,
        Most_Frequent_Cropping_Pattern: "Mustard-Boro-T.Aman",
        number_of_unique_cropping_pattern: 6,
        Average_Rainfall_Robi: 39.0,
        Average_Rainfall_Kharif1: 272.0,
        Average_Rainfall_Kharif2: 1414.0,
        Average_Temp_Robi: 20.58,
        Average_Temp_Kharif1: 21.56,
        Average_Temp_Kharif2: 31.42,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Homna",
        Lat: 23.6853,
        Lng: 90.76141,
        Most_Frequent_Cropping_Pattern: "Boro-B.Aman",
        number_of_unique_cropping_pattern: 6,
        Average_Rainfall_Robi: 69.0,
        Average_Rainfall_Kharif1: 473.0,
        Average_Rainfall_Kharif2: 1589.0,
        Average_Temp_Robi: 18.82,
        Average_Temp_Kharif1: 27.19,
        Average_Temp_Kharif2: 28.02,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Muladi",
        Lat: 22.90076,
        Lng: 90.38853,
        Most_Frequent_Cropping_Pattern: "Grasspea-Fallow-T.Aman",
        number_of_unique_cropping_pattern: 6,
        Average_Rainfall_Robi: 86.0,
        Average_Rainfall_Kharif1: 371.0,
        Average_Rainfall_Kharif2: 1704.0,
        Average_Temp_Robi: 21.26,
        Average_Temp_Kharif1: 28.19,
        Average_Temp_Kharif2: 28.5,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Chadpur-Sadar",
        Lat: 23.22272,
        Lng: 90.67982,
        Most_Frequent_Cropping_Pattern: "Boro-Fallow-T.Aman",
        number_of_unique_cropping_pattern: 6,
        Average_Rainfall_Robi: 194.0,
        Average_Rainfall_Kharif1: 802.0,
        Average_Rainfall_Kharif2: 1034.0,
        Average_Temp_Robi: 21.22,
        Average_Temp_Kharif1: 27.76,
        Average_Temp_Kharif2: 27.99,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Godagari",
        Lat: 24.56562,
        Lng: 88.40756,
        Most_Frequent_Cropping_Pattern: "Boro-Fallow-T.Aman",
        number_of_unique_cropping_pattern: 5,
        Average_Rainfall_Robi: 46.0,
        Average_Rainfall_Kharif1: 232.0,
        Average_Rainfall_Kharif2: 1276.0,
        Average_Temp_Robi: 20.57,
        Average_Temp_Kharif1: 27.88,
        Average_Temp_Kharif2: 28.69,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Ishwardi",
        Lat: 24.12978,
        Lng: 89.064,
        Most_Frequent_Cropping_Pattern: "others",
        number_of_unique_cropping_pattern: 5,
        Average_Rainfall_Robi: 56.0,
        Average_Rainfall_Kharif1: 332.0,
        Average_Rainfall_Kharif2: 1267.0,
        Average_Temp_Robi: 19.8,
        Average_Temp_Kharif1: 27.84,
        Average_Temp_Kharif2: 28.43,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Raujan",
        Lat: 22.53493,
        Lng: 91.91742,
        Most_Frequent_Cropping_Pattern: "Grasspea-Fallow-T.Aman",
        number_of_unique_cropping_pattern: 5,
        Average_Rainfall_Robi: 88.0,
        Average_Rainfall_Kharif1: 453.0,
        Average_Rainfall_Kharif2: 2336.0,
        Average_Temp_Robi: 21.84,
        Average_Temp_Kharif1: 27.19,
        Average_Temp_Kharif2: 28.83,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Debohata",
        Lat: 22.59529,
        Lng: 89.00171,
        Most_Frequent_Cropping_Pattern: "Vegetable-Vegetable-Vegetable",
        number_of_unique_cropping_pattern: 4,
        Average_Rainfall_Robi: 85.0,
        Average_Rainfall_Kharif1: 276.0,
        Average_Rainfall_Kharif2: 1365.0,
        Average_Temp_Robi: 21.64,
        Average_Temp_Kharif1: 28.99,
        Average_Temp_Kharif2: 29.07,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Tangail-Sadar",
        Lat: 24.25952,
        Lng: 89.87803,
        Most_Frequent_Cropping_Pattern: "Boro-Fallow-Fallow",
        number_of_unique_cropping_pattern: 4,
        Average_Rainfall_Robi: 59.0,
        Average_Rainfall_Kharif1: 465.0,
        Average_Rainfall_Kharif2: 1751.0,
        Average_Temp_Robi: 20.62,
        Average_Temp_Kharif1: 26.56,
        Average_Temp_Kharif2: 27.99,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Jamalgonj",
        Lat: 25.0319,
        Lng: 89.03315,
        Most_Frequent_Cropping_Pattern: "Boro-Fallow-Fallow",
        number_of_unique_cropping_pattern: 4,
        Average_Rainfall_Robi: 105.0,
        Average_Rainfall_Kharif1: 680.0,
        Average_Rainfall_Kharif2: 1615.0,
        Average_Temp_Robi: 20.91,
        Average_Temp_Kharif1: 25.46,
        Average_Temp_Kharif2: 27.38,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Rajarhat",
        Lat: 25.80065,
        Lng: 89.54069,
        Most_Frequent_Cropping_Pattern: "Boro-Fallow-T.Aman",
        number_of_unique_cropping_pattern: 4,
        Average_Rainfall_Robi: 39.0,
        Average_Rainfall_Kharif1: 272.0,
        Average_Rainfall_Kharif2: 1414.0,
        Average_Temp_Robi: 20.58,
        Average_Temp_Kharif1: 27.985,
        Average_Temp_Kharif2: 27.99,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Faridpur",
        Lat: 23.60612,
        Lng: 89.84064,
        Most_Frequent_Cropping_Pattern: "Boro-Fallow-Fallow",
        number_of_unique_cropping_pattern: 4,
        Average_Rainfall_Robi: 48.0,
        Average_Rainfall_Kharif1: 318.0,
        Average_Rainfall_Kharif2: 1283.0,
        Average_Temp_Robi: 19.82,
        Average_Temp_Kharif1: 27.82,
        Average_Temp_Kharif2: 28.29,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Kamarkhanda",
        Lat: 24.37037,
        Lng: 89.65147,
        Most_Frequent_Cropping_Pattern: "Mustard-Boro-T.Aman",
        number_of_unique_cropping_pattern: 4,
        Average_Rainfall_Robi: 48.0,
        Average_Rainfall_Kharif1: 318.0,
        Average_Rainfall_Kharif2: 1283.0,
        Average_Temp_Robi: 19.81,
        Average_Temp_Kharif1: 28.47,
        Average_Temp_Kharif2: 27.21,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Bheramara",
        Lat: 24.02151,
        Lng: 88.99171,
        Most_Frequent_Cropping_Pattern: "Wheat-Jute-T.Aman",
        number_of_unique_cropping_pattern: 4,
        Average_Rainfall_Robi: 41.4,
        Average_Rainfall_Kharif1: 201.5,
        Average_Rainfall_Kharif2: 1310.4,
        Average_Temp_Robi: 19.99,
        Average_Temp_Kharif1: 28.62,
        Average_Temp_Kharif2: 29.27,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Kolaroa",
        Lat: 22.85955,
        Lng: 89.04235,
        Most_Frequent_Cropping_Pattern: "Wheat-Jute-T.Aman",
        number_of_unique_cropping_pattern: 4,
        Average_Rainfall_Robi: 85.0,
        Average_Rainfall_Kharif1: 276.0,
        Average_Rainfall_Kharif2: 1365.0,
        Average_Temp_Robi: 21.64,
        Average_Temp_Kharif1: 28.99,
        Average_Temp_Kharif2: 29.07,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Kushtia-Sadar",
        Lat: 23.83623,
        Lng: 89.10272,
        Most_Frequent_Cropping_Pattern: "Fallow-Aus-T.Aman",
        number_of_unique_cropping_pattern: 4,
        Average_Rainfall_Robi: 45.0,
        Average_Rainfall_Kharif1: 233.0,
        Average_Rainfall_Kharif2: 1230.0,
        Average_Temp_Robi: 20.56,
        Average_Temp_Kharif1: 25.92,
        Average_Temp_Kharif2: 28.85,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Chitolmari",
        Lat: 22.79184,
        Lng: 89.87692,
        Most_Frequent_Cropping_Pattern: "Boro-B.Aman",
        number_of_unique_cropping_pattern: 4,
        Average_Rainfall_Robi: 61.0,
        Average_Rainfall_Kharif1: 341.0,
        Average_Rainfall_Kharif2: 1473.0,
        Average_Temp_Robi: 21.79,
        Average_Temp_Kharif1: 28.76,
        Average_Temp_Kharif2: 28.49,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Bhandaria",
        Lat: 22.48538,
        Lng: 90.0664,
        Most_Frequent_Cropping_Pattern: "Mungbean-Fallow-T.Aman",
        number_of_unique_cropping_pattern: 4,
        Average_Rainfall_Robi: 95.0,
        Average_Rainfall_Kharif1: 387.0,
        Average_Rainfall_Kharif2: 1666.0,
        Average_Temp_Robi: 20.99,
        Average_Temp_Kharif1: 27.93,
        Average_Temp_Kharif2: 28.23,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Tarash",
        Lat: 24.44677,
        Lng: 89.33085,
        Most_Frequent_Cropping_Pattern: "Boro-Fallow-T.Aman",
        number_of_unique_cropping_pattern: 4,
        Average_Rainfall_Robi: 48.0,
        Average_Rainfall_Kharif1: 318.0,
        Average_Rainfall_Kharif2: 1283.0,
        Average_Temp_Robi: 19.8,
        Average_Temp_Kharif1: 27.8,
        Average_Temp_Kharif2: 28.5,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Kotiyadi",
        Lat: 24.2459,
        Lng: 90.7937,
        Most_Frequent_Cropping_Pattern: "Boro-Fallow-Fallow",
        number_of_unique_cropping_pattern: 4,
        Average_Rainfall_Robi: 59.0,
        Average_Rainfall_Kharif1: 465.0,
        Average_Rainfall_Kharif2: 1751.0,
        Average_Temp_Robi: 20.62,
        Average_Temp_Kharif1: 26.56,
        Average_Temp_Kharif2: 27.99,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Terkhada",
        Lat: 22.91268,
        Lng: 89.66386,
        Most_Frequent_Cropping_Pattern: "Fallow-B.Aus+B.Aman",
        number_of_unique_cropping_pattern: 4,
        Average_Rainfall_Robi: 94.0,
        Average_Rainfall_Kharif1: 304.0,
        Average_Rainfall_Kharif2: 1413.0,
        Average_Temp_Robi: 21.81,
        Average_Temp_Kharif1: 28.79,
        Average_Temp_Kharif2: 28.79,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Baghmara",
        Lat: 23.03169,
        Lng: 90.20882,
        Most_Frequent_Cropping_Pattern: "Mustard-Boro-Fallow",
        number_of_unique_cropping_pattern: 4,
        Average_Rainfall_Robi: 46.0,
        Average_Rainfall_Kharif1: 232.0,
        Average_Rainfall_Kharif2: 1276.0,
        Average_Temp_Robi: 20.27,
        Average_Temp_Kharif1: 27.89,
        Average_Temp_Kharif2: 20.51,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Atpara",
        Lat: 24.79949,
        Lng: 90.86337,
        Most_Frequent_Cropping_Pattern: "Boro-Fallow-Fallow",
        number_of_unique_cropping_pattern: 4,
        Average_Rainfall_Robi: 51.0,
        Average_Rainfall_Kharif1: 503.0,
        Average_Rainfall_Kharif2: 1673.0,
        Average_Temp_Robi: 20.13,
        Average_Temp_Kharif1: 26.46,
        Average_Temp_Kharif2: 27.72,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Nobabgonj",
        Lat: 25.41997,
        Lng: 89.09019,
        Most_Frequent_Cropping_Pattern: "Boro-Fallow-T.Aman",
        number_of_unique_cropping_pattern: 4,
        Average_Rainfall_Robi: 31.0,
        Average_Rainfall_Kharif1: 281.0,
        Average_Rainfall_Kharif2: 1617.0,
        Average_Temp_Robi: 19.45,
        Average_Temp_Kharif1: 19.7,
        Average_Temp_Kharif2: 34.97,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Nagarkanda",
        Lat: 23.42,
        Lng: 89.85,
        Most_Frequent_Cropping_Pattern: "Onion-Jute-Fallow",
        number_of_unique_cropping_pattern: 4,
        Average_Rainfall_Robi: 65.0,
        Average_Rainfall_Kharif1: 419.0,
        Average_Rainfall_Kharif2: 1401.0,
        Average_Temp_Robi: 20.44,
        Average_Temp_Kharif1: 27.6,
        Average_Temp_Kharif2: 28.32,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Louhojong",
        Lat: 23.4691,
        Lng: 90.32891,
        Most_Frequent_Cropping_Pattern: "others",
        number_of_unique_cropping_pattern: 4,
        Average_Rainfall_Robi: 72.0,
        Average_Rainfall_Kharif1: 515.0,
        Average_Rainfall_Kharif2: 1515.0,
        Average_Temp_Robi: 21.09,
        Average_Temp_Kharif1: 27.86,
        Average_Temp_Kharif2: 28.28,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Jhinaigati",
        Lat: 25.17069,
        Lng: 90.0619,
        Most_Frequent_Cropping_Pattern: "Boro-Fallow-T.Aman",
        number_of_unique_cropping_pattern: 4,
        Average_Rainfall_Robi: 59.0,
        Average_Rainfall_Kharif1: 465.0,
        Average_Rainfall_Kharif2: 1751.0,
        Average_Temp_Robi: 20.62,
        Average_Temp_Kharif1: 26.55,
        Average_Temp_Kharif2: 34.82,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Panchari",
        Lat: 23.31992,
        Lng: 91.89647,
        Most_Frequent_Cropping_Pattern: "others",
        number_of_unique_cropping_pattern: 3,
        Average_Rainfall_Robi: 87.0,
        Average_Rainfall_Kharif1: 424.0,
        Average_Rainfall_Kharif2: 2002.0,
        Average_Temp_Robi: 22.54,
        Average_Temp_Kharif1: 27.92,
        Average_Temp_Kharif2: 28.05,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Satkania",
        Lat: 22.09852,
        Lng: 92.07456,
        Most_Frequent_Cropping_Pattern: "others",
        number_of_unique_cropping_pattern: 3,
        Average_Rainfall_Robi: 88.0,
        Average_Rainfall_Kharif1: 453.0,
        Average_Rainfall_Kharif2: 2336.0,
        Average_Temp_Robi: 21.85,
        Average_Temp_Kharif1: 27.19,
        Average_Temp_Kharif2: 27.92,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Dhamrai",
        Lat: 23.9455,
        Lng: 90.12108,
        Most_Frequent_Cropping_Pattern: "Boro-Fallow-Fallow",
        number_of_unique_cropping_pattern: 3,
        Average_Rainfall_Robi: 72.0,
        Average_Rainfall_Kharif1: 515.0,
        Average_Rainfall_Kharif2: 1515.0,
        Average_Temp_Robi: 24.15,
        Average_Temp_Kharif1: 27.86,
        Average_Temp_Kharif2: 28.48,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Thanchi",
        Lat: 21.87441,
        Lng: 92.39327,
        Most_Frequent_Cropping_Pattern: "others",
        number_of_unique_cropping_pattern: 3,
        Average_Rainfall_Robi: 87.0,
        Average_Rainfall_Kharif1: 424.0,
        Average_Rainfall_Kharif2: 2002.0,
        Average_Temp_Robi: 22.54,
        Average_Temp_Kharif1: 27.92,
        Average_Temp_Kharif2: 28.05,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Chouhali",
        Lat: 24.2,
        Lng: 89.75,
        Most_Frequent_Cropping_Pattern: "Potato-B.Aman",
        number_of_unique_cropping_pattern: 3,
        Average_Rainfall_Robi: 48.0,
        Average_Rainfall_Kharif1: 318.0,
        Average_Rainfall_Kharif2: 1238.0,
        Average_Temp_Robi: 19.96,
        Average_Temp_Kharif1: 27.78,
        Average_Temp_Kharif2: 28.49,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Sonagazi",
        Lat: 22.85044,
        Lng: 91.40117,
        Most_Frequent_Cropping_Pattern: "Boro-Fallow-T.Aman",
        number_of_unique_cropping_pattern: 3,
        Average_Rainfall_Robi: 83.0,
        Average_Rainfall_Kharif1: 644.0,
        Average_Rainfall_Kharif2: 2303.0,
        Average_Temp_Robi: 21.99,
        Average_Temp_Kharif1: 27.19,
        Average_Temp_Kharif2: 22.31,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Doulotpur",
        Lat: 24.43742,
        Lng: 91.44986,
        Most_Frequent_Cropping_Pattern: "Boro-Fallow-Fallow",
        number_of_unique_cropping_pattern: 3,
        Average_Rainfall_Robi: 70.0,
        Average_Rainfall_Kharif1: 443.0,
        Average_Rainfall_Kharif2: 1363.0,
        Average_Temp_Robi: 20.98,
        Average_Temp_Kharif1: 27.66,
        Average_Temp_Kharif2: 28.38,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Sathiya",
        Lat: 24.07434,
        Lng: 89.527,
        Most_Frequent_Cropping_Pattern: "Mustard-Boro-Fallow",
        number_of_unique_cropping_pattern: 3,
        Average_Rainfall_Robi: 49.0,
        Average_Rainfall_Kharif1: 320.0,
        Average_Rainfall_Kharif2: 1244.0,
        Average_Temp_Robi: 20.62,
        Average_Temp_Kharif1: 28.32,
        Average_Temp_Kharif2: 28.77,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Goyainghat",
        Lat: 25.09214,
        Lng: 91.9807,
        Most_Frequent_Cropping_Pattern: "Boro-Fallow-Fallow",
        number_of_unique_cropping_pattern: 3,
        Average_Rainfall_Robi: 79.0,
        Average_Rainfall_Kharif1: 1099.0,
        Average_Rainfall_Kharif2: 2915.0,
        Average_Temp_Robi: 21.22,
        Average_Temp_Kharif1: 25.93,
        Average_Temp_Kharif2: 28.1,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Tarakanda",
        Lat: 24.83423,
        Lng: 90.43516,
        Most_Frequent_Cropping_Pattern: "Boro-Fallow-T.Aman",
        number_of_unique_cropping_pattern: 2,
        Average_Rainfall_Robi: 59.0,
        Average_Rainfall_Kharif1: 465.0,
        Average_Rainfall_Kharif2: 1751.0,
        Average_Temp_Robi: 20.62,
        Average_Temp_Kharif1: 26.56,
        Average_Temp_Kharif2: 28.0,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Ramgora",
        Lat: 24.59888,
        Lng: 88.70085,
        Most_Frequent_Cropping_Pattern: "others",
        number_of_unique_cropping_pattern: 2,
        Average_Rainfall_Robi: 87.0,
        Average_Rainfall_Kharif1: 424.0,
        Average_Rainfall_Kharif2: 2002.0,
        Average_Temp_Robi: 24.09,
        Average_Temp_Kharif1: 27.93,
        Average_Temp_Kharif2: 28.12,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Ajmirigonj",
        Lat: 24.57,
        Lng: 91.29,
        Most_Frequent_Cropping_Pattern: "Boro-Fallow-Fallow",
        number_of_unique_cropping_pattern: 2,
        Average_Rainfall_Robi: 105.0,
        Average_Rainfall_Kharif1: 680.0,
        Average_Rainfall_Kharif2: 1615.0,
        Average_Temp_Robi: 20.58,
        Average_Temp_Kharif1: 25.46,
        Average_Temp_Kharif2: 27.44,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Purbadhola",
        Lat: 24.92065,
        Lng: 90.60799,
        Most_Frequent_Cropping_Pattern: "Boro-Fallow-Fallow",
        number_of_unique_cropping_pattern: 2,
        Average_Rainfall_Robi: 59.0,
        Average_Rainfall_Kharif1: 465.0,
        Average_Rainfall_Kharif2: 1751.0,
        Average_Temp_Robi: 20.26,
        Average_Temp_Kharif1: 26.76,
        Average_Temp_Kharif2: 27.99,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Kahalu",
        Lat: 24.83282,
        Lng: 89.26784,
        Most_Frequent_Cropping_Pattern: "Boro-Fallow-T.Aman",
        number_of_unique_cropping_pattern: 2,
        Average_Rainfall_Robi: 38.0,
        Average_Rainfall_Kharif1: 208.0,
        Average_Rainfall_Kharif2: 1294.0,
        Average_Temp_Robi: 20.3,
        Average_Temp_Kharif1: 27.79,
        Average_Temp_Kharif2: 28.41,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "fulbaria",
        Lat: 24.625,
        Lng: 90.2667,
        Most_Frequent_Cropping_Pattern: "Boro-Fallow-T.Aman",
        number_of_unique_cropping_pattern: 2,
        Average_Rainfall_Robi: 46.0,
        Average_Rainfall_Kharif1: 483.0,
        Average_Rainfall_Kharif2: 1721.0,
        Average_Temp_Robi: 20.51,
        Average_Temp_Kharif1: 27.78,
        Average_Temp_Kharif2: 28.34,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Chatkhil",
        Lat: 23.06255,
        Lng: 90.96674,
        Most_Frequent_Cropping_Pattern: "Boro-Fallow-Fallow",
        number_of_unique_cropping_pattern: 2,
        Average_Rainfall_Robi: 99.0,
        Average_Rainfall_Kharif1: 741.0,
        Average_Rainfall_Kharif2: 2489.0,
        Average_Temp_Robi: 21.97,
        Average_Temp_Kharif1: 27.73,
        Average_Temp_Kharif2: 28.24,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Fulbaria",
        Lat: 23.72564,
        Lng: 90.40662,
        Most_Frequent_Cropping_Pattern: "others",
        number_of_unique_cropping_pattern: 1,
        Average_Rainfall_Robi: 46.0,
        Average_Rainfall_Kharif1: 483.0,
        Average_Rainfall_Kharif2: 1721.0,
        Average_Temp_Robi: 20.51,
        Average_Temp_Kharif1: 27.78,
        Average_Temp_Kharif2: 28.34,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
    {
        Upazila: "Roujan",
        Lat: 22.53493,
        Lng: 91.91742,
        Most_Frequent_Cropping_Pattern: "others",
        number_of_unique_cropping_pattern: 1,
        Average_Rainfall_Robi: 88.0,
        Average_Rainfall_Kharif1: 453.0,
        Average_Rainfall_Kharif2: 2336.0,
        Average_Temp_Robi: 21.84,
        Average_Temp_Kharif1: 27.19,
        Average_Temp_Kharif2: 28.83,
        id_x: null,
        cp_x: null,
        id_y: null,
        cp_y: null,
    },
];

function getDistanceFromLatLonInKm(lat1, lon1, lat2, lon2) {
    var R = 6371; // Radius of the earth in km
    var dLat = deg2rad(lat2 - lat1); // deg2rad below
    var dLon = deg2rad(lon2 - lon1);
    var a =
        Math.sin(dLat / 2) * Math.sin(dLat / 2) +
        Math.cos(deg2rad(lat1)) *
            Math.cos(deg2rad(lat2)) *
            Math.sin(dLon / 2) *
            Math.sin(dLon / 2);
    var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
    var d = R * c; // Distance in km
    return d;
}

function deg2rad(deg) {
    return deg * (Math.PI / 180);
}

const findClosest = (lat, lng) => {
    let closest = null;
    let minDistance = Infinity;
    for (let i = 0; i < locationData.length; i++) {
        const distance = getDistanceFromLatLonInKm(
            lat,
            lng,
            locationData[i].Lat,
            locationData[i].Lng
        );
        if (distance < minDistance) {
            minDistance = distance;
            closest = locationData[i];
        }
    }
    return closest;
};

export { findClosest, locationData };
