//dummy data
const data = [
    {
        name: "Sabbir Ahmed",
        email: "asabbir311@gmail.com",
        dataset_name: "Cropping patterns of Bangladesh",
    },
];

const croppingPatternData = [
    {
        id: "001",
        cp: "Boro-Fallow-T.Aman",
        "area(ha)": "2306005",
        "%of NAC": "26.919",
        "No. of district": "63",
        "No of upazila": "426",
    },
    {
        id: "002",
        cp: "Boro-Fallow-Fallow",
        "area(ha)": "1139530",
        "%of NAC": "13.302",
        "No. of district": "59",
        "No of upazila": "342",
    },
    {
        id: "003",
        cp: "Fallow-Fallow-T.Aman",
        "area(ha)": "509480",
        "%of NAC": "5.947",
        "No. of district": "36",
        "No of upazila": "162",
    },
    {
        id: "004",
        cp: "Boro-Aus-T.Aman",
        "area(ha)": "209015",
        "%of NAC": "2.440",
        "No. of district": "47",
        "No of upazila": "177",
    },
    {
        id: "005",
        cp: "Fallow-Aus-T.Aman",
        "area(ha)": "193275",
        "%of NAC": "2.256",
        "No. of district": "30",
        "No of upazila": "108",
    },
    {
        id: "006",
        cp: "Mustard-Boro-T.Aman",
        "area(ha)": "184620",
        "%of NAC": "2.155",
        "No. of district": "51",
        "No of upazila": "203",
    },
    {
        id: "007",
        cp: "Boro-B.Aman",
        "area(ha)": "183070",
        "%of NAC": "2.137",
        "No. of district": "32",
        "No of upazila": "113",
    },
    {
        id: "008",
        cp: "Potato-Boro-T.Aman",
        "area(ha)": "180380",
        "%of NAC": "2.106",
        "No. of district": "33",
        "No of upazila": "115",
    },
    {
        id: "009",
        cp: "Wheat-Jute-T.Aman",
        "area(ha)": "147210",
        "%of NAC": "1.718",
        "No. of district": "43",
        "No of upazila": "216",
    },
    {
        id: "010",
        cp: "Vegetable-Vegetable-Vegetable",
        "area(ha)": "143270",
        "%of NAC": "1.672",
        "No. of district": "61",
        "No of upazila": "283",
    },
    {
        id: "011",
        cp: "Mustard-Boro-Fallow",
        "area(ha)": "143130",
        "%of NAC": "1.671",
        "No. of district": "37",
        "No of upazila": "112",
    },
    {
        id: "012",
        cp: "Grasspea-Fallow-T.Aman",
        "area(ha)": "108150",
        "%of NAC": "1.262",
        "No. of district": "25",
        "No of upazila": "80",
    },
    {
        id: "013",
        cp: "Maize-Fallow-T.Aman",
        "area(ha)": "101460",
        "%of NAC": "1.184",
        "No. of district": "39",
        "No of upazila": "126",
    },
    {
        id: "014",
        cp: "Wheat-Fallow-T.Aman",
        "area(ha)": "90910",
        "%of NAC": "1.061",
        "No. of district": "39",
        "No of upazila": "100",
    },
    {
        id: "015",
        cp: "Mungbean-Fallow-T.Aman",
        "area(ha)": "89650",
        "%of NAC": "1.047",
        "No. of district": "22",
        "No of upazila": "70",
    },
    {
        id: "016",
        cp: "Grasspea-Aus-T.Aman",
        "area(ha)": "81610",
        "%of NAC": "0.953",
        "No. of district": "19",
        "No of upazila": "61",
    },
    {
        id: "017",
        cp: "Vegetable-Fallow-T.Aman",
        "area(ha)": "74710",
        "%of NAC": "0.872",
        "No. of district": "45",
        "No of upazila": "170",
    },
    {
        id: "018",
        cp: "Vegetable-Vegetable-Fallow",
        "area(ha)": "63935",
        "%of NAC": "0.746",
        "No. of district": "59",
        "No of upazila": "168",
    },
    {
        id: "019",
        cp: "Onion-Jute-T.Aman",
        "area(ha)": "54185",
        "%of NAC": "0.633",
        "No. of district": "39",
        "No of upazila": "102",
    },
    {
        id: "020",
        cp: "Mungbean-Aus-T.Aman",
        "area(ha)": "53730",
        "%of NAC": "0.627",
        "No. of district": "14",
        "No of upazila": "43",
    },
    {
        id: "021",
        cp: "Chilli-Fallow-T.Aman",
        "area(ha)": "52995",
        "%of NAC": "0.619",
        "No. of district": "45",
        "No of upazila": "146",
    },
    {
        id: "022",
        cp: "Lentil-Jute-T.Aman",
        "area(ha)": "51875",
        "%of NAC": "0.606",
        "No. of district": "34",
        "No of upazila": "96",
    },
    {
        id: "023",
        cp: "Vegetable-Vegetable-T.Aman",
        "area(ha)": "51745",
        "%of NAC": "0.604",
        "No. of district": "49",
        "No of upazila": "127",
    },
    {
        id: "024",
        cp: "Wheat-Jute-Fallow",
        "area(ha)": "48700",
        "%of NAC": "0.568",
        "No. of district": "32",
        "No of upazila": "82",
    },
    {
        id: "025",
        cp: "Potato-Maize-T.Aman",
        "area(ha)": "47690",
        "%of NAC": "0.557",
        "No. of district": "19",
        "No of upazila": "68",
    },
    {
        id: "026",
        cp: "Boro-Aus-Fallow",
        "area(ha)": "45865",
        "%of NAC": "0.535",
        "No. of district": "34",
        "No of upazila": "71",
    },
    {
        id: "027",
        cp: "Onion-Jute-Fallow",
        "area(ha)": "45200",
        "%of NAC": "0.528",
        "No. of district": "29",
        "No of upazila": "67",
    },
    {
        id: "028",
        cp: "Boro-Jute-T.Aman",
        "area(ha)": "40440",
        "%of NAC": "0.472",
        "No. of district": "19",
        "No of upazila": "56",
    },
    {
        id: "029",
        cp: "Felon-Fallow-T.Aman",
        "area(ha)": "37675",
        "%of NAC": "0.440",
        "No. of district": "14",
        "No of upazila": "53",
    },
    {
        id: "030",
        cp: "Mustard-Boro-B.Aman",
        "area(ha)": "36520",
        "%of NAC": "0.426",
        "No. of district": "14",
        "No of upazila": "32",
    },
    {
        id: "031",
        cp: "Wheat-Aus-T.Aman",
        "area(ha)": "36425",
        "%of NAC": "0.425",
        "No. of district": "35",
        "No of upazila": "93",
    },
    {
        id: "032",
        cp: "Mustard-Jute-T.Aman",
        "area(ha)": "32740",
        "%of NAC": "0.382",
        "No. of district": "29",
        "No of upazila": "64",
    },
    {
        id: "033",
        cp: "Lentil-Jute-Fallow",
        "area(ha)": "32360",
        "%of NAC": "0.378",
        "No. of district": "27",
        "No of upazila": "67",
    },
    {
        id: "034",
        cp: "Boro-Fish",
        "area(ha)": "31400",
        "%of NAC": "0.367",
        "No. of district": "3",
        "No of upazila": "17a",
    },
    {
        id: "035",
        cp: "Vegetable-Fallow-Fallow",
        "area(ha)": "31115",
        "%of NAC": "0.363",
        "No. of district": "35",
        "No of upazila": "84",
    },
    {
        id: "036",
        cp: "Groundnut-Fallow-T.Aman",
        "area(ha)": "29210",
        "%of NAC": "0.341",
        "No. of district": "23",
        "No of upazila": "60",
    },
    {
        id: "037",
        cp: "Vegetable-Aus-T.Aman",
        "area(ha)": "28700",
        "%of NAC": "0.335",
        "No. of district": "42",
        "No of upazila": "87",
    },
    {
        id: "038",
        cp: "Water Melon-Fallow-T.Aman",
        "area(ha)": "28340",
        "%of NAC": "0.331",
        "No. of district": "17",
        "No of upazila": "49",
    },
    {
        id: "039",
        cp: "Potato-Jute-T.Aman",
        "area(ha)": "28310",
        "%of NAC": "0.330",
        "No. of district": "36",
        "No of upazila": "95",
    },
    {
        id: "040",
        cp: "Potato-B.Aman",
        "area(ha)": "23900",
        "%of NAC": "0.279",
        "No. of district": "9",
        "No of upazila": "25",
    },
    {
        id: "041",
        cp: "Soybean-Fallow-T.Aman",
        "area(ha)": "23670",
        "%of NAC": "0.276",
        "No. of district": "5",
        "No of upazila": "10",
    },
    {
        id: "042",
        cp: "Soybean-Aus-T.Aman",
        "area(ha)": "23170",
        "%of NAC": "0.270",
        "No. of district": "5",
        "No of upazila": "8",
    },
    {
        id: "043",
        cp: "Potato-Fallow-T.Aman",
        "area(ha)": "22715",
        "%of NAC": "0.265",
        "No. of district": "34",
        "No of upazila": "108",
    },
    {
        id: "044",
        cp: "Potato-Aus-T.Aman",
        "area(ha)": "22405",
        "%of NAC": "0.262",
        "No. of district": "29",
        "No of upazila": "79",
    },
    {
        id: "045",
        cp: "Wheat-Mungbean-T.Aman",
        "area(ha)": "21760",
        "%of NAC": "0.254",
        "No. of district": "20",
        "No of upazila": "50",
    },
    {
        id: "046",
        cp: "Grasspea-B.Aman",
        "area(ha)": "21480",
        "%of NAC": "0.251",
        "No. of district": "21",
        "No of upazila": "52",
    },
    {
        id: "047",
        cp: "Maize-Jute-Fallow",
        "area(ha)": "21425",
        "%of NAC": "0.250",
        "No. of district": "19",
        "No of upazila": "33",
    },
    {
        id: "048",
        cp: "Maize-Jute-T.Aman",
        "area(ha)": "21325",
        "%of NAC": "0.249",
        "No. of district": "18",
        "No of upazila": "38",
    },
    {
        id: "049",
        cp: "Vegetable-Boro-T.Aman",
        "area(ha)": "21220",
        "%of NAC": "0.248",
        "No. of district": "22",
        "No of upazila": "42",
    },
    {
        id: "050",
        cp: "Grasspea-Jute-Fallow",
        "area(ha)": "21000",
        "%of NAC": "0.245",
        "No. of district": "21",
        "No of upazila": "39",
    },
    {
        id: "051",
        cp: "Fish-T.Aman",
        "area(ha)": "20400",
        "%of NAC": "0.238",
        "No. of district": "3",
        "No of upazila": "8",
    },
    {
        id: "052",
        cp: "Soybean-Jute-T.Aman",
        "area(ha)": "20000",
        "%of NAC": "0.233",
        "No. of district": "4",
        "No of upazila": "6",
    },
    {
        id: "053",
        cp: "Potato-Boro-Fallow",
        "area(ha)": "19360",
        "%of NAC": "0.226",
        "No. of district": "17",
        "No of upazila": "27",
    },
    {
        id: "054",
        cp: "Mustard-Boro-Aus",
        "area(ha)": "18140",
        "%of NAC": "0.212",
        "No. of district": "10",
        "No of upazila": "16",
    },
    {
        id: "055",
        cp: "Mustard-B.Aman",
        "area(ha)": "17210",
        "%of NAC": "0.201",
        "No. of district": "12",
        "No of upazila": "24",
    },
    {
        id: "056",
        cp: "Mustard-Jute-Fallow",
        "area(ha)": "17180",
        "%of NAC": "0.201",
        "No. of district": "16",
        "No of upazila": "35",
    },
    {
        id: "057",
        cp: "Sweet Potato-Fallow-T.Aman",
        "area(ha)": "16990",
        "%of NAC": "0.198",
        "No. of district": "31",
        "No of upazila": "103",
    },
    {
        id: "058",
        cp: "Groundnut-Fallow-Fallow",
        "area(ha)": "16485",
        "%of NAC": "0.192",
        "No. of district": "35",
        "No of upazila": "76",
    },
    {
        id: "059",
        cp: "Boro-Jute-Fallow",
        "area(ha)": "16370",
        "%of NAC": "0.191",
        "No. of district": "19",
        "No of upazila": "25",
    },
    {
        id: "060",
        cp: "Fallow-B.Aman",
        "area(ha)": "16360",
        "%of NAC": "0.191",
        "No. of district": "15",
        "No of upazila": "29",
    },
    {
        id: "061",
        cp: "Wheat-Maize-T.Aman",
        "area(ha)": "16320",
        "%of NAC": "0.191",
        "No. of district": "9",
        "No of upazila": "14",
    },
    {
        id: "062",
        cp: "Wheat-Aus-Fallow",
        "area(ha)": "16200",
        "%of NAC": "0.189",
        "No. of district": "17",
        "No of upazila": "26",
    },
    {
        id: "063",
        cp: "Vegetable-Aus-Fallow",
        "area(ha)": "15940",
        "%of NAC": "0.186",
        "No. of district": "23",
        "No of upazila": "41",
    },
    {
        id: "064",
        cp: "Tobacco-Jute-T.Aman",
        "area(ha)": "15200",
        "%of NAC": "0.177",
        "No. of district": "9",
        "No of upazila": "19",
    },
    {
        id: "065",
        cp: "Mustard-Fallow-T.Aman",
        "area(ha)": "14870",
        "%of NAC": "0.174",
        "No. of district": "33",
        "No of upazila": "84",
    },
    {
        id: "066",
        cp: "Groundnut- Aus-T.Aman",
        "area(ha)": "14535",
        "%of NAC": "0.170",
        "No. of district": "10",
        "No of upazila": "18",
    },
    {
        id: "067",
        cp: "Potato-Jute-Fallow",
        "area(ha)": "14515",
        "%of NAC": "0.169",
        "No. of district": "25",
        "No of upazila": "53",
    },
    {
        id: "068",
        cp: "Boro-Sesbania-T.Aman",
        "area(ha)": "14490",
        "%of NAC": "0.169",
        "No. of district": "20",
        "No of upazila": "33",
    },
    {
        id: "069",
        cp: "Chilli-Aus-T.Aman",
        "area(ha)": "14240",
        "%of NAC": "0.166",
        "No. of district": "21",
        "No of upazila": "38",
    },
    {
        id: "070",
        cp: "Wheat-B.Aman",
        "area(ha)": "13835",
        "%of NAC": "0.162",
        "No. of district": "16",
        "No of upazila": "32",
    },
    {
        id: "071",
        cp: "Mustard-Aus-T.Aman",
        "area(ha)": "13790",
        "%of NAC": "0.161",
        "No. of district": "30",
        "No of upazila": "52",
    },
    {
        id: "072",
        cp: "Fallow-Jute-T.Aman",
        "area(ha)": "13620",
        "%of NAC": "0.159",
        "No. of district": "18",
        "No of upazila": "32",
    },
    {
        id: "073",
        cp: "Maize-Aus-Fallow",
        "area(ha)": "13615",
        "%of NAC": "0.159",
        "No. of district": "14",
        "No of upazila": "18",
    },
    {
        id: "074",
        cp: "Garlic-Jute-Fallow",
        "area(ha)": "13475",
        "%of NAC": "0.157",
        "No. of district": "26",
        "No of upazila": "48",
    },
    {
        id: "075",
        cp: "Boro-Vegetable (Float/Norm)",
        "area(ha)": "13335",
        "%of NAC": "0.156",
        "No. of district": "27",
        "No of upazila": "36",
    },
    {
        id: "076",
        cp: "Boro-Fallow-Blackgram",
        "area(ha)": "13270",
        "%of NAC": "0.155",
        "No. of district": "27",
        "No of upazila": "44",
    },
    {
        id: "077",
        cp: "Chilli-Jute-Fallow",
        "area(ha)": "13260",
        "%of NAC": "0.155",
        "No. of district": "22",
        "No of upazila": "54",
    },
    {
        id: "078",
        cp: "Vegetable-Jute-Fallow",
        "area(ha)": "13185",
        "%of NAC": "0.154",
        "No. of district": "26",
        "No of upazila": "47",
    },
    {
        id: "079",
        cp: "Garlic-Jute-T.Aman",
        "area(ha)": "13090",
        "%of NAC": "0.153",
        "No. of district": "38",
        "No of upazila": "78",
    },
    {
        id: "080",
        cp: "Wheat-Aus-Blackgram",
        "area(ha)": "13000",
        "%of NAC": "0.152",
        "No. of district": "6",
        "No of upazila": "8",
    },
    {
        id: "081",
        cp: "Maize-Fallow-Fallow",
        "area(ha)": "12920",
        "%of NAC": "0.151",
        "No. of district": "22",
        "No of upazila": "38",
    },
    {
        id: "082",
        cp: "Lentil-Fallow-T.Aman",
        "area(ha)": "12680",
        "%of NAC": "0.148",
        "No. of district": "29",
        "No of upazila": "68",
    },
    {
        id: "083",
        cp: "Potato-Vegetable-T.Aman",
        "area(ha)": "12620",
        "%of NAC": "0.147",
        "No. of district": "30",
        "No of upazila": "59",
    },
    {
        id: "084",
        cp: "Lentil-Sesame-T.Aman",
        "area(ha)": "12450",
        "%of NAC": "0.145",
        "No. of district": "14",
        "No of upazila": "33",
    },
    {
        id: "085",
        cp: "Fallow-Aus+Non-rice (jhum)",
        "area(ha)": "11900",
        "%of NAC": "0.139",
        "No. of district": "3",
        "No of upazila": "20",
    },
    {
        id: "086",
        cp: "Onion-Vegtable-Vegetable",
        "area(ha)": "11735",
        "%of NAC": "0.137",
        "No. of district": "39",
        "No of upazila": "87",
    },
    {
        id: "087",
        cp: "Fallow-Sesame-T.Aman",
        "area(ha)": "11640",
        "%of NAC": "0.136",
        "No. of district": "13",
        "No of upazila": "20",
    },
    {
        id: "088",
        cp: "Vegetable-Jute-T.Aman",
        "area(ha)": "11305",
        "%of NAC": "0.132",
        "No. of district": "25",
        "No of upazila": "51",
    },
    {
        id: "089",
        cp: "Lentil-Aus-T.Aman",
        "area(ha)": "11255",
        "%of NAC": "0.131",
        "No. of district": "25",
        "No of upazila": "46",
    },
    {
        id: "090",
        cp: "Onion-B.Aman",
        "area(ha)": "10905",
        "%of NAC": "0.127",
        "No. of district": "14",
        "No of upazila": "27",
    },
    {
        id: "091",
        cp: "Garlic-B.Aman",
        "area(ha)": "10850",
        "%of NAC": "0.127",
        "No. of district": "15",
        "No of upazila": "21",
    },
    {
        id: "092",
        cp: "Potato-Sesbania",
        "area(ha)": "10770",
        "%of NAC": "0.126",
        "No. of district": "5",
        "No of upazila": "15",
    },
    {
        id: "093",
        cp: "Wheat-Sesame-T.Aman",
        "area(ha)": "10650",
        "%of NAC": "0.124",
        "No. of district": "15",
        "No of upazila": "33",
    },
    {
        id: "094",
        cp: "Water Melon-Aus-T.Aman",
        "area(ha)": "10355",
        "%of NAC": "0.121",
        "No. of district": "11",
        "No of upazila": "14",
    },
    {
        id: "095",
        cp: "Grasspea-Jute-T.Aman",
        "area(ha)": "10300",
        "%of NAC": "0.120",
        "No. of district": "25",
        "No of upazila": "43",
    },
    {
        id: "096",
        cp: "Potato-Maize-Fallow",
        "area(ha)": "9640",
        "%of NAC": "0.113",
        "No. of district": "10",
        "No of upazila": "16",
    },
    {
        id: "097",
        cp: "Chilli-Fallow-Fallow",
        "area(ha)": "9265",
        "%of NAC": "0.108",
        "No. of district": "40",
        "No of upazila": "66",
    },
    {
        id: "098",
        cp: "Sesame-Fallow-T.Aman",
        "area(ha)": "9265",
        "%of NAC": "0.108",
        "No. of district": "19",
        "No of upazila": "31",
    },
    {
        id: "099",
        cp: "Felon-Aus-T.Aman",
        "area(ha)": "9245",
        "%of NAC": "0.108",
        "No. of district": "7",
        "No of upazila": "16",
    },
    {
        id: "100",
        cp: "Boro-Sesbania-Fallow",
        "area(ha)": "9180",
        "%of NAC": "0.107",
        "No. of district": "12",
        "No of upazila": "19",
    },
    {
        id: "101",
        cp: "Chilli-B.Aman",
        "area(ha)": "9120",
        "%of NAC": "0.106",
        "No. of district": "10",
        "No of upazila": "23",
    },
    {
        id: "102",
        cp: "Chilli-Vegetable-Fallow",
        "area(ha)": "8810",
        "%of NAC": "0.103",
        "No. of district": "44",
        "No of upazila": "104",
    },
    {
        id: "103",
        cp: "Onion-Aus-Fallow",
        "area(ha)": "8705",
        "%of NAC": "0.102",
        "No. of district": "12",
        "No of upazila": "17",
    },
    {
        id: "104",
        cp: "Fallow-Fallow-Blackgram",
        "area(ha)": "8695",
        "%of NAC": "0.102",
        "No. of district": "34",
        "No of upazila": "59",
    },
    {
        id: "105",
        cp: "Boro-Vegetable-T.Aman",
        "area(ha)": "8660",
        "%of NAC": "0.101",
        "No. of district": "9",
        "No of upazila": "16",
    },
    {
        id: "106",
        cp: "Boro-Aus-Blackgram",
        "area(ha)": "8540",
        "%of NAC": "0.100",
        "No. of district": "5",
        "No of upazila": "5",
    },
    {
        id: "107",
        cp: "Sweet Potato-Fallow-Fallow",
        "area(ha)": "7980",
        "%of NAC": "0.093",
        "No. of district": "37",
        "No of upazila": "98",
    },
    {
        id: "108",
        cp: "Mustard-Boro-Aus-T.Aman",
        "area(ha)": "7850",
        "%of NAC": "0.092",
        "No. of district": "14",
        "No of upazila": "30",
    },
    {
        id: "109",
        cp: "Blackgram-B.Aman",
        "area(ha)": "7625",
        "%of NAC": "0.089",
        "No. of district": "11",
        "No of upazila": "24",
    },
    {
        id: "110",
        cp: "Chilli-Aus-Fallow",
        "area(ha)": "7565",
        "%of NAC": "0.088",
        "No. of district": "14",
        "No of upazila": "27",
    },
    {
        id: "111",
        cp: "Tobacco-Maize-T.Aman",
        "area(ha)": "7470",
        "%of NAC": "0.087",
        "No. of district": "5",
        "No of upazila": "12",
    },
    {
        id: "112",
        cp: "Potato-Boro-Aus",
        "area(ha)": "7420",
        "%of NAC": "0.087",
        "No. of district": "4",
        "No of upazila": "6",
    },
    {
        id: "113",
        cp: "Coriander-Jute-Fallow",
        "area(ha)": "7390",
        "%of NAC": "0.086",
        "No. of district": "15",
        "No of upazila": "25",
    },
    {
        id: "114",
        cp: "Chilli-Jute-T.Aman",
        "area(ha)": "7250",
        "%of NAC": "0.085",
        "No. of district": "20",
        "No of upazila": "35",
    },
    {
        id: "115",
        cp: "Fallow-Vegetable-T.Aman",
        "area(ha)": "7130",
        "%of NAC": "0.083",
        "No. of district": "16",
        "No of upazila": "29",
    },
    {
        id: "116",
        cp: "Maize-Vegetable-Fallow",
        "area(ha)": "7120",
        "%of NAC": "0.083",
        "No. of district": "14",
        "No of upazila": "19",
    },
    {
        id: "117",
        cp: "Vegetable-Boro-Fallow",
        "area(ha)": "7100",
        "%of NAC": "0.083",
        "No. of district": "9",
        "No of upazila": "10",
    },
    {
        id: "118",
        cp: "Lentil-Mungbean-T.Aman",
        "area(ha)": "6955",
        "%of NAC": "0.081",
        "No. of district": "11",
        "No of upazila": "22",
    },
    {
        id: "119",
        cp: "Lentil-B.Aman",
        "area(ha)": "6550",
        "%of NAC": "0.076",
        "No. of district": "16",
        "No of upazila": "30",
    },
    {
        id: "120",
        cp: "Onion-Fallow-T.Aman",
        "area(ha)": "6380",
        "%of NAC": "0.074",
        "No. of district": "32",
        "No of upazila": "64",
    },
    {
        id: "121",
        cp: "Lentil-Vegetable-Vegetable",
        "area(ha)": "6330",
        "%of NAC": "0.074",
        "No. of district": "19",
        "No of upazila": "30",
    },
    {
        id: "122",
        cp: "Mustard-Maize-T.Aman",
        "area(ha)": "6310",
        "%of NAC": "0.074",
        "No. of district": "9",
        "No of upazila": "19",
    },
    {
        id: "123",
        cp: "Wheat-Vegetable-Vegetable",
        "area(ha)": "6100",
        "%of NAC": "0.071",
        "No. of district": "16",
        "No of upazila": "21",
    },
    {
        id: "124",
        cp: "Tobacco-Aus-T.Aman",
        "area(ha)": "6040",
        "%of NAC": "0.071",
        "No. of district": "5",
        "No of upazila": "12",
    },
    {
        id: "125",
        cp: "Soybean-B.Aman",
        "area(ha)": "5650",
        "%of NAC": "0.066",
        "No. of district": "4",
        "No of upazila": "4",
    },
    {
        id: "126",
        cp: "Boro-Fallow-T.Aman +Fish",
        "area(ha)": "5410",
        "%of NAC": "0.063",
        "No. of district": "3",
        "No of upazila": "7",
    },
    {
        id: "127",
        cp: "Tobacco-Fallow-T.Aman",
        "area(ha)": "5310",
        "%of NAC": "0.062",
        "No. of district": "7",
        "No of upazila": "15",
    },
    {
        id: "128",
        cp: "Wheat-Vegetable-T.Aman",
        "area(ha)": "5205",
        "%of NAC": "0.061",
        "No. of district": "15",
        "No of upazila": "25",
    },
    {
        id: "129",
        cp: "Vegetable-B.Aman",
        "area(ha)": "5200",
        "%of NAC": "0.061",
        "No. of district": "9",
        "No of upazila": "17",
    },
    {
        id: "130",
        cp: "Maize-B.Aman",
        "area(ha)": "5030",
        "%of NAC": "0.059",
        "No. of district": "10",
        "No of upazila": "15",
    },
    {
        id: "131",
        cp: "Mustard-Aus-Fallow",
        "area(ha)": "4935",
        "%of NAC": "0.058",
        "No. of district": "15",
        "No of upazila": "22",
    },
    {
        id: "132",
        cp: "Maize-Mungbean-T.Aman",
        "area(ha)": "4900",
        "%of NAC": "0.057",
        "No. of district": "1",
        "No of upazila": "3",
    },
    {
        id: "133",
        cp: "Mustard-Mungbean-T.Aman",
        "area(ha)": "4710",
        "%of NAC": "0.055",
        "No. of district": "12",
        "No of upazila": "18",
    },
    {
        id: "134",
        cp: "Chickpea-Fallow-T.Aman",
        "area(ha)": "4700",
        "%of NAC": "0.055",
        "No. of district": "12",
        "No of upazila": "32",
    },
    {
        id: "135",
        cp: "Grasspea-Boro-Fallow",
        "area(ha)": "4690",
        "%of NAC": "0.055",
        "No. of district": "8",
        "No of upazila": "12",
    },
    {
        id: "136",
        cp: "Coriander-Jute-T.Aman",
        "area(ha)": "4625",
        "%of NAC": "0.054",
        "No. of district": "17",
        "No of upazila": "30",
    },
    {
        id: "137",
        cp: "Lentil-Aus-Fallow",
        "area(ha)": "4570",
        "%of NAC": "0.053",
        "No. of district": "11",
        "No of upazila": "15",
    },
    {
        id: "138",
        cp: "Vegetable-Maize-T.Aman",
        "area(ha)": "4500",
        "%of NAC": "0.053",
        "No. of district": "9",
        "No of upazila": "15",
    },
    {
        id: "139",
        cp: "Garlic-Vegetable-Vegetable",
        "area(ha)": "4385",
        "%of NAC": "0.051",
        "No. of district": "27",
        "No of upazila": "68",
    },
    {
        id: "140",
        cp: "Potato-Maize-Aus",
        "area(ha)": "4300",
        "%of NAC": "0.050",
        "No. of district": "3",
        "No of upazila": "4",
    },
    {
        id: "141",
        cp: "Onion-Aus-T.Aman",
        "area(ha)": "4260",
        "%of NAC": "0.050",
        "No. of district": "17",
        "No of upazila": "26",
    },
    {
        id: "142",
        cp: "Tobacco-Jute-Fallow",
        "area(ha)": "4050",
        "%of NAC": "0.047",
        "No. of district": "4",
        "No of upazila": "8",
    },
    {
        id: "143",
        cp: "Wheat-Jute-Blackgram",
        "area(ha)": "3910",
        "%of NAC": "0.046",
        "No. of district": "7",
        "No of upazila": "9",
    },
    {
        id: "144",
        cp: "Wheat-Fallow-Fallow",
        "area(ha)": "3810",
        "%of NAC": "0.044",
        "No. of district": "6",
        "No of upazila": "8",
    },
    {
        id: "145",
        cp: "Wheat-Chilli-Fallow",
        "area(ha)": "3780",
        "%of NAC": "0.044",
        "No. of district": "7",
        "No of upazila": "9",
    },
    {
        id: "146",
        cp: "Maize-Maize-Fallow",
        "area(ha)": "3720",
        "%of NAC": "0.043",
        "No. of district": "3",
        "No of upazila": "5",
    },
    {
        id: "147",
        cp: "Wheat-Fallow-T.Aman (Orchard)",
        "area(ha)": "3700",
        "%of NAC": "0.043",
        "No. of district": "1",
        "No of upazila": "2",
    },
    {
        id: "148",
        cp: "Garlic-Fallow-T.Aman",
        "area(ha)": "3680",
        "%of NAC": "0.043",
        "No. of district": "31",
        "No of upazila": "59",
    },
    {
        id: "149",
        cp: "Lentil-Sesame-Fallow",
        "area(ha)": "3680",
        "%of NAC": "0.043",
        "No. of district": "15",
        "No of upazila": "20",
    },
    {
        id: "150",
        cp: "Chilli-Boro-Jute",
        "area(ha)": "3600",
        "%of NAC": "0.042",
        "No. of district": "2",
        "No of upazila": "3",
    },
    {
        id: "151",
        cp: "Maize-Fallow-Blackgram",
        "area(ha)": "3600",
        "%of NAC": "0.042",
        "No. of district": "4",
        "No of upazila": "4",
    },
    {
        id: "152",
        cp: "Vegetable-Fallow-Blackgram",
        "area(ha)": "3525",
        "%of NAC": "0.041",
        "No. of district": "16",
        "No of upazila": "33",
    },
    {
        id: "153",
        cp: "Fallow-B.Aus+B.Aman",
        "area(ha)": "3470",
        "%of NAC": "0.041",
        "No. of district": "3",
        "No of upazila": "5",
    },
    {
        id: "154",
        cp: "Sweet Potato-Jute-Fallow",
        "area(ha)": "3380",
        "%of NAC": "0.039",
        "No. of district": "13",
        "No of upazila": "21",
    },
    {
        id: "155",
        cp: "Mustard-Sesame-T.Aman",
        "area(ha)": "3360",
        "%of NAC": "0.039",
        "No. of district": "12",
        "No of upazila": "15",
    },
    {
        id: "156",
        cp: "Vegetable-Onion-Aus",
        "area(ha)": "3200",
        "%of NAC": "0.037",
        "No. of district": "3",
        "No of upazila": "3",
    },
    {
        id: "157",
        cp: "Tobacco-Aus-Fallow",
        "area(ha)": "3180",
        "%of NAC": "0.037",
        "No. of district": "5",
        "No of upazila": "10",
    },
    {
        id: "158",
        cp: "Coriander-Fallow-Fallow",
        "area(ha)": "3175",
        "%of NAC": "0.037",
        "No. of district": "41",
        "No of upazila": "64",
    },
    {
        id: "159",
        cp: "Potato-Boro-Aus-T.Aman",
        "area(ha)": "3140",
        "%of NAC": "0.037",
        "No. of district": "5",
        "No of upazila": "9",
    },
    {
        id: "160",
        cp: "Onion-Sesame-T.Aman",
        "area(ha)": "3080",
        "%of NAC": "0.036",
        "No. of district": "4",
        "No of upazila": "6",
    },
    {
        id: "161",
        cp: "Maize-Maize-T.Aman",
        "area(ha)": "3070",
        "%of NAC": "0.036",
        "No. of district": "6",
        "No of upazila": "8",
    },
    {
        id: "162",
        cp: "Wheat-Maize-Fallow",
        "area(ha)": "3070",
        "%of NAC": "0.036",
        "No. of district": "2",
        "No of upazila": "4",
    },
    {
        id: "163",
        cp: "Sesame-Fallow-Blackgram",
        "area(ha)": "3060",
        "%of NAC": "0.036",
        "No. of district": "6",
        "No of upazila": "10",
    },
    {
        id: "164",
        cp: "Maize-Aus-Vegetable",
        "area(ha)": "3000",
        "%of NAC": "0.035",
        "No. of district": "3",
        "No of upazila": "4",
    },
    {
        id: "165",
        cp: "Mustard-Boro-Jute",
        "area(ha)": "3000",
        "%of NAC": "0.035",
        "No. of district": "5",
        "No of upazila": "7",
    },
    {
        id: "166",
        cp: "Mustard-Boro-Jute-T.Aman",
        "area(ha)": "2980",
        "%of NAC": "0.035",
        "No. of district": "7",
        "No of upazila": "13",
    },
    {
        id: "167",
        cp: "Maize-Aus-T.Aman",
        "area(ha)": "2970",
        "%of NAC": "0.035",
        "No. of district": "17",
        "No of upazila": "27",
    },
    {
        id: "168",
        cp: "Lentil-Maize-T.Aman",
        "area(ha)": "2920",
        "%of NAC": "0.034",
        "No. of district": "4",
        "No of upazila": "8",
    },
    {
        id: "169",
        cp: "Wheat-Mungbean-Fallow",
        "area(ha)": "2875",
        "%of NAC": "0.034",
        "No. of district": "5",
        "No of upazila": "7",
    },
    {
        id: "170",
        cp: "Groundnut-B.Aman",
        "area(ha)": "2820",
        "%of NAC": "0.033",
        "No. of district": "5",
        "No of upazila": "7",
    },
    {
        id: "171",
        cp: "Lentil-Fallow-Fallow(Orchard)",
        "area(ha)": "2780",
        "%of NAC": "0.032",
        "No. of district": "3",
        "No of upazila": "5",
    },
    {
        id: "172",
        cp: "Fallow-Sesame+B.Aman",
        "area(ha)": "2750",
        "%of NAC": "0.032",
        "No. of district": "5",
        "No of upazila": "7",
    },
    {
        id: "173",
        cp: "Potato-Groundnut-T.Aman",
        "area(ha)": "2720",
        "%of NAC": "0.032",
        "No. of district": "3",
        "No of upazila": "5",
    },
    {
        id: "174",
        cp: "Soybean-Fallow-Fallow",
        "area(ha)": "2710",
        "%of NAC": "0.032",
        "No. of district": "3",
        "No of upazila": "4",
    },
    {
        id: "175",
        cp: "Grasspea-Boro-B.Aman",
        "area(ha)": "2700",
        "%of NAC": "0.032",
        "No. of district": "3",
        "No of upazila": "3",
    },
    {
        id: "176",
        cp: "Lentil-Vegetable-T.Aman",
        "area(ha)": "2660",
        "%of NAC": "0.031",
        "No. of district": "11",
        "No of upazila": "11",
    },
    {
        id: "177",
        cp: "Vegetable-Groundnut-T.Aman",
        "area(ha)": "2660",
        "%of NAC": "0.031",
        "No. of district": "4",
        "No of upazila": "5",
    },
    {
        id: "178",
        cp: "Pea-B.Aman",
        "area(ha)": "2620",
        "%of NAC": "0.031",
        "No. of district": "11",
        "No of upazila": "16",
    },
    {
        id: "179",
        cp: "Garlic-Mungbean-T.Aman",
        "area(ha)": "2500",
        "%of NAC": "0.029",
        "No. of district": "1",
        "No of upazila": "2",
    },
    {
        id: "180",
        cp: "Garlic-Aus-T.Aman",
        "area(ha)": "2400",
        "%of NAC": "0.028",
        "No. of district": "13",
        "No of upazila": "20",
    },
    {
        id: "181",
        cp: "Millet(Kaon)-Fallow-T.Aman",
        "area(ha)": "2390",
        "%of NAC": "0.028",
        "No. of district": "6",
        "No of upazila": "6",
    },
    {
        id: "182",
        cp: "Muskmelon-Fallow-T.Aman",
        "area(ha)": "2310",
        "%of NAC": "0.027",
        "No. of district": "10",
        "No of upazila": "23",
    },
    {
        id: "183",
        cp: "Potato-Aus-Fallow",
        "area(ha)": "2310",
        "%of NAC": "0.027",
        "No. of district": "13",
        "No of upazila": "16",
    },
    {
        id: "184",
        cp: "Tobacco-Boro-T.Aman",
        "area(ha)": "2300",
        "%of NAC": "0.027",
        "No. of district": "3",
        "No of upazila": "4",
    },
    {
        id: "185",
        cp: "Blackgram-Jute-Fallow",
        "area(ha)": "2295",
        "%of NAC": "0.027",
        "No. of district": "12",
        "No of upazila": "16",
    },
    {
        id: "186",
        cp: "Grasspea-Fallow-Fallow",
        "area(ha)": "2295",
        "%of NAC": "0.027",
        "No. of district": "9",
        "No of upazila": "11",
    },
    {
        id: "187",
        cp: "Fallow-Fallow-T.Aman +Fish",
        "area(ha)": "2200",
        "%of NAC": "0.026",
        "No. of district": "2",
        "No of upazila": "2",
    },
    {
        id: "188",
        cp: "Potato-Maize-Vegetable",
        "area(ha)": "2190",
        "%of NAC": "0.026",
        "No. of district": "4",
        "No of upazila": "4",
    },
    {
        id: "189",
        cp: "Coriander-Fallow-T.Aman",
        "area(ha)": "2185",
        "%of NAC": "0.026",
        "No. of district": "31",
        "No of upazila": "62",
    },
    {
        id: "190",
        cp: "Vegetable-Maize-Fallow",
        "area(ha)": "2180",
        "%of NAC": "0.025",
        "No. of district": "6",
        "No of upazila": "7",
    },
    {
        id: "191",
        cp: "Potato-Boro-Jute-T.Aman",
        "area(ha)": "2160",
        "%of NAC": "0.025",
        "No. of district": "4",
        "No of upazila": "5",
    },
    {
        id: "192",
        cp: "Sweet Potato-Aus-T.Aman",
        "area(ha)": "2150",
        "%of NAC": "0.025",
        "No. of district": "2",
        "No of upazila": "2",
    },
    {
        id: "193",
        cp: "Wheat-Mung-Fallow(Orchard)",
        "area(ha)": "2150",
        "%of NAC": "0.025",
        "No. of district": "2",
        "No of upazila": "3",
    },
    {
        id: "194",
        cp: "Onion-Sesame+B.Aman",
        "area(ha)": "2100",
        "%of NAC": "0.025",
        "No. of district": "2",
        "No of upazila": "3",
    },
    {
        id: "195",
        cp: "Pea-Jute-Fallow",
        "area(ha)": "2100",
        "%of NAC": "0.025",
        "No. of district": "10",
        "No of upazila": "15",
    },
    {
        id: "196",
        cp: "Sunflower-Fallow-T.Aman",
        "area(ha)": "2100",
        "%of NAC": "0.025",
        "No. of district": "7",
        "No of upazila": "23",
    },
    {
        id: "197",
        cp: "Coriander-Vegetable-Fallow",
        "area(ha)": "2090",
        "%of NAC": "0.024",
        "No. of district": "20",
        "No of upazila": "29",
    },
    {
        id: "198",
        cp: "Potato-Chilli-Fallow",
        "area(ha)": "2070",
        "%of NAC": "0.024",
        "No. of district": "10",
        "No of upazila": "17",
    },
    {
        id: "199",
        cp: "Potato-Sesame-T.Aman",
        "area(ha)": "2060",
        "%of NAC": "0.024",
        "No. of district": "15",
        "No of upazila": "23",
    },
    {
        id: "200",
        cp: "Blackgram(Fodder)-Boro-B.Aman",
        "area(ha)": "2000",
        "%of NAC": "0.023",
        "No. of district": "1",
        "No of upazila": "1",
    },
    {
        id: "201",
        cp: "Wheat-Maize-Vegetable",
        "area(ha)": "2000",
        "%of NAC": "0.023",
        "No. of district": "2",
        "No of upazila": "2",
    },
    {
        id: "202",
        cp: "Pea-Fallow-T.Aman",
        "area(ha)": "1950",
        "%of NAC": "0.023",
        "No. of district": "18",
        "No of upazila": "27",
    },
    {
        id: "203",
        cp: "Potato-Sesame-Fallow",
        "area(ha)": "1930",
        "%of NAC": "0.023",
        "No. of district": "6",
        "No of upazila": "10",
    },
    {
        id: "204",
        cp: "Blackgram-Jute-T.Aman",
        "area(ha)": "1900",
        "%of NAC": "0.022",
        "No. of district": "11",
        "No of upazila": "14",
    },
    {
        id: "205",
        cp: "Mustard-Aus-Blackgram",
        "area(ha)": "1900",
        "%of NAC": "0.022",
        "No. of district": "2",
        "No of upazila": "2",
    },
    {
        id: "206",
        cp: "Mustard-Jute-Vegetable",
        "area(ha)": "1900",
        "%of NAC": "0.022",
        "No. of district": "3",
        "No of upazila": "5",
    },
    {
        id: "207",
        cp: "Wheat-Aus-Onion",
        "area(ha)": "1900",
        "%of NAC": "0.022",
        "No. of district": "1",
        "No of upazila": "1",
    },
    {
        id: "208",
        cp: "Blackcumin-Jute-Fallow",
        "area(ha)": "1840",
        "%of NAC": "0.021",
        "No. of district": "6",
        "No of upazila": "12",
    },
    {
        id: "209",
        cp: "Maize-Sesame-T.Aman",
        "area(ha)": "1835",
        "%of NAC": "0.021",
        "No. of district": "6",
        "No of upazila": "9",
    },
    {
        id: "210",
        cp: "Maize-Vegetable-T.Aman",
        "area(ha)": "1810",
        "%of NAC": "0.021",
        "No. of district": "11",
        "No of upazila": "12",
    },
    {
        id: "211",
        cp: "Millet(Kaon)+Sesame-Fallow",
        "area(ha)": "1810",
        "%of NAC": "0.021",
        "No. of district": "5",
        "No of upazila": "7",
    },
    {
        id: "212",
        cp: "Onion-Aus-Blackgram",
        "area(ha)": "1810",
        "%of NAC": "0.021",
        "No. of district": "5",
        "No of upazila": "6",
    },
    {
        id: "213",
        cp: "Grasspea-Boro-Aus",
        "area(ha)": "1800",
        "%of NAC": "0.021",
        "No. of district": "1",
        "No of upazila": "1",
    },
    {
        id: "214",
        cp: "Grasspea-Sesame+B.Aman",
        "area(ha)": "1800",
        "%of NAC": "0.021",
        "No. of district": "2",
        "No of upazila": "2",
    },
    {
        id: "215",
        cp: "Grasspea-Sesame-T.Aman",
        "area(ha)": "1790",
        "%of NAC": "0.021",
        "No. of district": "5",
        "No of upazila": "6",
    },
    {
        id: "216",
        cp: "Grasspea-Sesbania-Fallow",
        "area(ha)": "1780",
        "%of NAC": "0.021",
        "No. of district": "4",
        "No of upazila": "4",
    },
    {
        id: "217",
        cp: "Mustard-B.Aus+B.Aman",
        "area(ha)": "1780",
        "%of NAC": "0.021",
        "No. of district": "4",
        "No of upazila": "4",
    },
    {
        id: "218",
        cp: "Blackgram-Aus-T.Aman",
        "area(ha)": "1735",
        "%of NAC": "0.020",
        "No. of district": "10",
        "No of upazila": "13",
    },
    {
        id: "219",
        cp: "Mustard-Sesame+B.Aman",
        "area(ha)": "1650",
        "%of NAC": "0.019",
        "No. of district": "3",
        "No of upazila": "4",
    },
    {
        id: "220",
        cp: "Tobacco-Sesbania-T.Aman",
        "area(ha)": "1620",
        "%of NAC": "0.019",
        "No. of district": "1",
        "No of upazila": "2",
    },
    {
        id: "221",
        cp: "Vegetable-Aus-Blackgram",
        "area(ha)": "1610",
        "%of NAC": "0.019",
        "No. of district": "4",
        "No of upazila": "4",
    },
    {
        id: "222",
        cp: "Grasspea-B.Aus+B.Aman",
        "area(ha)": "1580",
        "%of NAC": "0.018",
        "No. of district": "6",
        "No of upazila": "8",
    },
    {
        id: "223",
        cp: "Maize-Sesame-Fallow",
        "area(ha)": "1580",
        "%of NAC": "0.018",
        "No. of district": "6",
        "No of upazila": "8",
    },
    {
        id: "224",
        cp: "Groundnut- Aus-Fallow",
        "area(ha)": "1550",
        "%of NAC": "0.018",
        "No. of district": "5",
        "No of upazila": "5",
    },
    {
        id: "225",
        cp: "Wheat-Sesame-Fallow",
        "area(ha)": "1550",
        "%of NAC": "0.018",
        "No. of district": "7",
        "No of upazila": "8",
    },
    {
        id: "226",
        cp: "Groundnut-Jute-T.Aman",
        "area(ha)": "1530",
        "%of NAC": "0.018",
        "No. of district": "7",
        "No of upazila": "13",
    },
    {
        id: "227",
        cp: "Boro-Fallow-Maize",
        "area(ha)": "1500",
        "%of NAC": "0.018",
        "No. of district": "1",
        "No of upazila": "1",
    },
    {
        id: "228",
        cp: "Tobacco-Vegetable-Vegetable",
        "area(ha)": "1500",
        "%of NAC": "0.018",
        "No. of district": "1",
        "No of upazila": "1",
    },
    {
        id: "229",
        cp: "Onion-Maize-T.Aman",
        "area(ha)": "1490",
        "%of NAC": "0.017",
        "No. of district": "7",
        "No of upazila": "9",
    },
    {
        id: "230",
        cp: "Coriander-B.Aman",
        "area(ha)": "1480",
        "%of NAC": "0.017",
        "No. of district": "11",
        "No of upazila": "11",
    },
    {
        id: "231",
        cp: "Garlic-Aus-Fallow",
        "area(ha)": "1450",
        "%of NAC": "0.017",
        "No. of district": "12",
        "No of upazila": "15",
    },
    {
        id: "232",
        cp: "Vegetable-Jute-Vegetable",
        "area(ha)": "1450",
        "%of NAC": "0.017",
        "No. of district": "5",
        "No of upazila": "5",
    },
    {
        id: "233",
        cp: "Chilli-Vegetable-T.Aman",
        "area(ha)": "1405",
        "%of NAC": "0.016",
        "No. of district": "15",
        "No of upazila": "19",
    },
    {
        id: "234",
        cp: "Fallow-Aus-Fallow",
        "area(ha)": "1400",
        "%of NAC": "0.016",
        "No. of district": "3",
        "No of upazila": "3",
    },
    {
        id: "235",
        cp: "Maize-Boro-T.Aman",
        "area(ha)": "1400",
        "%of NAC": "0.016",
        "No. of district": "2",
        "No of upazila": "2",
    },
    {
        id: "236",
        cp: "Maize-Aus-Blackgram",
        "area(ha)": "1370",
        "%of NAC": "0.016",
        "No. of district": "3",
        "No of upazila": "3",
    },
    {
        id: "237",
        cp: "Cotton-Aus-Fallow",
        "area(ha)": "1330",
        "%of NAC": "0.016",
        "No. of district": "3",
        "No of upazila": "3",
    },
    {
        id: "238",
        cp: "Grasspea-Sesame-Fallow",
        "area(ha)": "1330",
        "%of NAC": "0.016",
        "No. of district": "7",
        "No of upazila": "10",
    },
    {
        id: "239",
        cp: "Groundnut-Fallow-Blackgram",
        "area(ha)": "1320",
        "%of NAC": "0.015",
        "No. of district": "3",
        "No of upazila": "3",
    },
    {
        id: "240",
        cp: "Wheat-Jute-Vegetable",
        "area(ha)": "1320",
        "%of NAC": "0.015",
        "No. of district": "6",
        "No of upazila": "6",
    },
    {
        id: "241",
        cp: "Pea-Aus-Vegetable",
        "area(ha)": "1310",
        "%of NAC": "0.015",
        "No. of district": "7",
        "No of upazila": "8",
    },
    {
        id: "242",
        cp: "Onion-Sesame-Fallow",
        "area(ha)": "1270",
        "%of NAC": "0.015",
        "No. of district": "8",
        "No of upazila": "9",
    },
    {
        id: "243",
        cp: "Blackcumin-Jute-T.Aman",
        "area(ha)": "1260",
        "%of NAC": "0.015",
        "No. of district": "6",
        "No of upazila": "11",
    },
    {
        id: "244",
        cp: "Sesame-Aus-Fallow",
        "area(ha)": "1190",
        "%of NAC": "0.014",
        "No. of district": "3",
        "No of upazila": "4",
    },
    {
        id: "245",
        cp: "Sesame-Aus-T.Aman",
        "area(ha)": "1180",
        "%of NAC": "0.014",
        "No. of district": "4",
        "No of upazila": "5",
    },
    {
        id: "246",
        cp: "Water Melon-Fallow-Fallow",
        "area(ha)": "1165",
        "%of NAC": "0.014",
        "No. of district": "9",
        "No of upazila": "12",
    },
    {
        id: "247",
        cp: "Pea-Vegetable-Fallow",
        "area(ha)": "1160",
        "%of NAC": "0.014",
        "No. of district": "4",
        "No of upazila": "5",
    },
    {
        id: "248",
        cp: "Potato-Mungbean-T.Aman",
        "area(ha)": "1140",
        "%of NAC": "0.013",
        "No. of district": "11",
        "No of upazila": "13",
    },
    {
        id: "249",
        cp: "Potato-Groundnut",
        "area(ha)": "1110",
        "%of NAC": "0.013",
        "No. of district": "5",
        "No of upazila": "8",
    },
    {
        id: "250",
        cp: "Tobacco-Fallow-Fallow",
        "area(ha)": "1045",
        "%of NAC": "0.012",
        "No. of district": "5",
        "No of upazila": "8",
    },
    {
        id: "251",
        cp: "Potato-Maize-Aus-Vegetable",
        "area(ha)": "1030",
        "%of NAC": "0.012",
        "No. of district": "3",
        "No of upazila": "3",
    },
    {
        id: "252",
        cp: "Fallow-Fallow-T.Aman (Orchard)",
        "area(ha)": "1000",
        "%of NAC": "0.012",
        "No. of district": "1",
        "No of upazila": "1",
    },
    {
        id: "253",
        cp: "Maize-Sesbania-Fallow",
        "area(ha)": "1000",
        "%of NAC": "0.012",
        "No. of district": "1",
        "No of upazila": "1",
    },
    {
        id: "254",
        cp: "Lentil-Sesame+B.Aman",
        "area(ha)": "980",
        "%of NAC": "0.011",
        "No. of district": "1",
        "No of upazila": "1",
    },
    {
        id: "255",
        cp: "Maize-Mungbean-Vegetable",
        "area(ha)": "950",
        "%of NAC": "0.011",
        "No. of district": "3",
        "No of upazila": "3",
    },
    {
        id: "256",
        cp: "Millet (Cheena)-Fallow-Fallow",
        "area(ha)": "935",
        "%of NAC": "0.011",
        "No. of district": "5",
        "No of upazila": "6",
    },
    {
        id: "257",
        cp: "Potato-Sweet gourd-Aus",
        "area(ha)": "910",
        "%of NAC": "0.011",
        "No. of district": "6",
        "No of upazila": "8",
    },
    {
        id: "258",
        cp: "Wheat-Fallow-Blackgram",
        "area(ha)": "900",
        "%of NAC": "0.011",
        "No. of district": "1",
        "No of upazila": "1",
    },
    {
        id: "259",
        cp: "Mustard-Fallow-Fallow",
        "area(ha)": "895",
        "%of NAC": "0.010",
        "No. of district": "9",
        "No of upazila": "13",
    },
    {
        id: "260",
        cp: "Coriander-Sesame-T.Aman",
        "area(ha)": "845",
        "%of NAC": "0.010",
        "No. of district": "5",
        "No of upazila": "5",
    },
    {
        id: "261",
        cp: "Vegetable-Boro-Aus-T.Aman",
        "area(ha)": "820",
        "%of NAC": "0.010",
        "No. of district": "4",
        "No of upazila": "5",
    },
    {
        id: "262",
        cp: "Vegetable-Boro-Jute",
        "area(ha)": "800",
        "%of NAC": "0.009",
        "No. of district": "2",
        "No of upazila": "3",
    },
    {
        id: "263",
        cp: "Potato+Sweetgourd-Aus-T.Aman",
        "area(ha)": "780",
        "%of NAC": "0.009",
        "No. of district": "3",
        "No of upazila": "5",
    },
    {
        id: "264",
        cp: "Wheat-Sesame-Blackgram(Orchard)",
        "area(ha)": "760",
        "%of NAC": "0.009",
        "No. of district": "3",
        "No of upazila": "3",
    },
    {
        id: "265",
        cp: "Sweet Potato-B.Aman",
        "area(ha)": "740",
        "%of NAC": "0.009",
        "No. of district": "6",
        "No of upazila": "6",
    },
    {
        id: "266",
        cp: "Mustard-Boro-Sesbania",
        "area(ha)": "700",
        "%of NAC": "0.008",
        "No. of district": "2",
        "No of upazila": "2",
    },
    {
        id: "267",
        cp: "Potato-Boro-Vegetable",
        "area(ha)": "700",
        "%of NAC": "0.008",
        "No. of district": "4",
        "No of upazila": "4",
    },
    {
        id: "268",
        cp: "Soybean-Aus-Fallow",
        "area(ha)": "700",
        "%of NAC": "0.008",
        "No. of district": "1",
        "No of upazila": "1",
    },
    {
        id: "269",
        cp: "Sweet Potato-Jute-T.Aman",
        "area(ha)": "675",
        "%of NAC": "0.008",
        "No. of district": "10",
        "No of upazila": "13",
    },
    {
        id: "270",
        cp: "Maize-Groundnut",
        "area(ha)": "620",
        "%of NAC": "0.007",
        "No. of district": "1",
        "No of upazila": "1",
    },
    {
        id: "271",
        cp: "Millet(Cheena)-Jute-Fallow",
        "area(ha)": "620",
        "%of NAC": "0.007",
        "No. of district": "2",
        "No of upazila": "2",
    },
    {
        id: "272",
        cp: "Sesame+B.Aman-Blackgram",
        "area(ha)": "600",
        "%of NAC": "0.007",
        "No. of district": "1",
        "No of upazila": "1",
    },
    {
        id: "273",
        cp: "Tobacco-Maize-Vegetable",
        "area(ha)": "600",
        "%of NAC": "0.007",
        "No. of district": "1",
        "No of upazila": "1",
    },
    {
        id: "274",
        cp: "Tobacco-Sesbania",
        "area(ha)": "600",
        "%of NAC": "0.007",
        "No. of district": "1",
        "No of upazila": "1",
    },
    {
        id: "275",
        cp: "Wheat-Aus-Cotton",
        "area(ha)": "600",
        "%of NAC": "0.007",
        "No. of district": "1",
        "No of upazila": "1",
    },
    {
        id: "276",
        cp: "Groundnut-Sesame-Fallow",
        "area(ha)": "590",
        "%of NAC": "0.007",
        "No. of district": "4",
        "No of upazila": "5",
    },
    {
        id: "277",
        cp: "Potato-Boro-Jute",
        "area(ha)": "590",
        "%of NAC": "0.007",
        "No. of district": "2",
        "No of upazila": "2",
    },
    {
        id: "278",
        cp: "Wheat-Ginger/Turmeric",
        "area(ha)": "580",
        "%of NAC": "0.007",
        "No. of district": "2",
        "No of upazila": "2",
    },
    {
        id: "279",
        cp: "Sweet Potato-Vegetable-Fallow",
        "area(ha)": "540",
        "%of NAC": "0.006",
        "No. of district": "5",
        "No of upazila": "9",
    },
    {
        id: "280",
        cp: "Water Melon-B.Aman",
        "area(ha)": "535",
        "%of NAC": "0.006",
        "No. of district": "3",
        "No of upazila": "3",
    },
    {
        id: "281",
        cp: "Garlic-Fallow-Fallow",
        "area(ha)": "530",
        "%of NAC": "0.006",
        "No. of district": "10",
        "No of upazila": "14",
    },
    {
        id: "282",
        cp: "Onion-Maize-Fallow",
        "area(ha)": "520",
        "%of NAC": "0.006",
        "No. of district": "4",
        "No of upazila": "4",
    },
    {
        id: "283",
        cp: "Potato-Onion-T.Aman",
        "area(ha)": "510",
        "%of NAC": "0.006",
        "No. of district": "2",
        "No of upazila": "2",
    },
    {
        id: "284",
        cp: "Felon-Aus-Fallow",
        "area(ha)": "470",
        "%of NAC": "0.005",
        "No. of district": "2",
        "No of upazila": "3",
    },
    {
        id: "285",
        cp: "Grasspea-Mungbean-T.Aman",
        "area(ha)": "440",
        "%of NAC": "0.005",
        "No. of district": "5",
        "No of upazila": "5",
    },
    {
        id: "286",
        cp: "Boro-Maize-Fallow",
        "area(ha)": "410",
        "%of NAC": "0.005",
        "No. of district": "2",
        "No of upazila": "2",
    },
    {
        id: "287",
        cp: "Potato+Maize-B.Aman",
        "area(ha)": "410",
        "%of NAC": "0.005",
        "No. of district": "2",
        "No of upazila": "3",
    },
    {
        id: "288",
        cp: "Felon-Fallow-Fallow",
        "area(ha)": "380",
        "%of NAC": "0.004",
        "No. of district": "3",
        "No of upazila": "4",
    },
    {
        id: "289",
        cp: "Groundnut-Millet(Kaon)-Fallow",
        "area(ha)": "380",
        "%of NAC": "0.004",
        "No. of district": "2",
        "No of upazila": "2",
    },
    {
        id: "290",
        cp: "Chickpea-Aus-T.Aman",
        "area(ha)": "375",
        "%of NAC": "0.004",
        "No. of district": "5",
        "No of upazila": "7",
    },
    {
        id: "291",
        cp: "Potato-Sesame-Aus",
        "area(ha)": "360",
        "%of NAC": "0.004",
        "No. of district": "4",
        "No of upazila": "4",
    },
    {
        id: "292",
        cp: "Boro-Chilli-Fallow",
        "area(ha)": "350",
        "%of NAC": "0.004",
        "No. of district": "1",
        "No of upazila": "1",
    },
    {
        id: "293",
        cp: "Boro-Maize-Blackgram",
        "area(ha)": "350",
        "%of NAC": "0.004",
        "No. of district": "1",
        "No of upazila": "1",
    },
    {
        id: "294",
        cp: "Sesame-B.Aman",
        "area(ha)": "330",
        "%of NAC": "0.004",
        "No. of district": "2",
        "No of upazila": "2",
    },
    {
        id: "295",
        cp: "Garlic+Muskmelon-B.Aman",
        "area(ha)": "320",
        "%of NAC": "0.004",
        "No. of district": "1",
        "No of upazila": "2",
    },
    {
        id: "296",
        cp: "Garlic+WaterMelon-B.Aman",
        "area(ha)": "320",
        "%of NAC": "0.004",
        "No. of district": "1",
        "No of upazila": "2",
    },
    {
        id: "297",
        cp: "Mungbean-Jute-Fallow",
        "area(ha)": "300",
        "%of NAC": "0.004",
        "No. of district": "6",
        "No of upazila": "8",
    },
    {
        id: "298",
        cp: "Sesame-Jute-T.Aman",
        "area(ha)": "290",
        "%of NAC": "0.003",
        "No. of district": "2",
        "No of upazila": "2",
    },
    {
        id: "299",
        cp: "Chickpea-Jute-T.Aman",
        "area(ha)": "270",
        "%of NAC": "0.003",
        "No. of district": "7",
        "No of upazila": "11",
    },
    {
        id: "300",
        cp: "Grasspea-Aus-Blackgram",
        "area(ha)": "250",
        "%of NAC": "0.003",
        "No. of district": "1",
        "No of upazila": "1",
    },
    {
        id: "301",
        cp: "Musk Melon-B.Aman",
        "area(ha)": "215",
        "%of NAC": "0.003",
        "No. of district": "2",
        "No of upazila": "5",
    },
    {
        id: "302",
        cp: "Potato+Maize-Vegetable-T.Aman",
        "area(ha)": "210",
        "%of NAC": "0.002",
        "No. of district": "2",
        "No of upazila": "2",
    },
    {
        id: "303",
        cp: "Mustard-Maize-Jute",
        "area(ha)": "200",
        "%of NAC": "0.002",
        "No. of district": "1",
        "No of upazila": "1",
    },
    {
        id: "304",
        cp: "Vegetab-Onion-Jute-T.Aman",
        "area(ha)": "200",
        "%of NAC": "0.002",
        "No. of district": "1",
        "No of upazila": "1",
    },
    {
        id: "305",
        cp: "Mungbean-Jute-T.Aman",
        "area(ha)": "180",
        "%of NAC": "0.002",
        "No. of district": "9",
        "No of upazila": "11",
    },
    {
        id: "306",
        cp: "Soybean-Jute-Fallow",
        "area(ha)": "140",
        "%of NAC": "0.002",
        "No. of district": "2",
        "No of upazila": "2",
    },
    {
        id: "307",
        cp: "Sunflower-Jute-Fallow",
        "area(ha)": "135",
        "%of NAC": "0.002",
        "No. of district": "3",
        "No of upazila": "3",
    },
    {
        id: "308",
        cp: "Mungbean-B.Aus+B.Aman",
        "area(ha)": "130",
        "%of NAC": "0.002",
        "No. of district": "4",
        "No of upazila": "4",
    },
    {
        id: "309",
        cp: "Musk Melon-Fallow-Fallow",
        "area(ha)": "125",
        "%of NAC": "0.001",
        "No. of district": "5",
        "No of upazila": "5",
    },
    {
        id: "310",
        cp: "Lentil-Mungbean-Jute-T.Aman",
        "area(ha)": "100",
        "%of NAC": "0.001",
        "No. of district": "1",
        "No of upazila": "1",
    },
    {
        id: "311",
        cp: "Mustard-Mungbean-Aus-T.Aman",
        "area(ha)": "100",
        "%of NAC": "0.001",
        "No. of district": "1",
        "No of upazila": "1",
    },
    {
        id: "312",
        cp: "Potato+S.gourd-M.bean-T.Aman",
        "area(ha)": "80",
        "%of NAC": "0.001",
        "No. of district": "1",
        "No of upazila": "1",
    },
    {
        id: "313",
        cp: "Tobacco-Mungbean-T.Aman",
        "area(ha)": "50",
        "%of NAC": "0.001",
        "No. of district": "1",
        "No of upazila": "1",
    },
    {
        id: "314",
        cp: "Tobacco-Mungbean-Vegetable",
        "area(ha)": "40",
        "%of NAC": "0.000",
        "No. of district": "1",
        "No of upazila": "1",
    },
    {
        id: "315",
        cp: "Mungbean-Aus-Fallow",
        "area(ha)": "20",
        "%of NAC": "0.000",
        "No. of district": "1",
        "No of upazila": "1",
    },
    {
        id: "316",
        cp: "Barley-Fallow-Fallow",
        "area(ha)": "15",
        "%of NAC": "0.000",
        "No. of district": "1",
        "No of upazila": "2",
    },
];

export { data, croppingPatternData };
